import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

type S = Record<string, CSSProperties>;

export const styles: S = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
    textAlign: 'center',
  },
  emailDisplay: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: '16px 20px',
    background: 'rgba(155, 93, 229, 0.05)',
    borderRadius: 12,
    border: '1px solid rgba(155, 93, 229, 0.15)',
  },
  emailIcon: {
    fontSize: 24,
  },
  email: {
    fontSize: 16,
    fontWeight: 600,
    color: theme.colors.text,
  },
  instructions: {
    fontSize: 14,
    lineHeight: 1.6,
    color: theme.colors.muted,
    margin: 0,
  },
  successMessage: {
    background: 'rgba(20, 184, 166, 0.1)',
    color: theme.colors.teal,
    border: '1px solid rgba(20, 184, 166, 0.3)',
    borderRadius: 12,
    padding: '12px 16px',
    fontSize: 14,
    fontWeight: 500,
  },
  errorMessage: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#ef4444',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: 12,
    padding: '12px 16px',
    fontSize: 14,
  },
  checkingStatus: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: '16px',
    fontSize: 13,
    color: theme.colors.muted,
  },
  spinner: {
    width: 16,
    height: 16,
    border: '2px solid rgba(155, 93, 229, 0.2)',
    borderTopColor: theme.colors.primary,
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  actions: {
    display: 'flex',
    gap: 12,
    marginTop: 8,
  },
  resendButton: {
    flex: 1,
    height: 40,
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
    color: '#fff',
    backgroundImage: theme.gradients.innovator,
    boxShadow: theme.shadows.primary,
    transition: 'transform 0.2s, box-shadow 0.2s',
    fontSize: 14,
    fontWeight: 600,
  },
  backButton: {
    flex: 1,
    height: 40,
    border: '2px solid rgba(155, 93, 229, 0.2)',
    borderRadius: 10,
    cursor: 'pointer',
    color: theme.colors.muted,
    background: 'transparent',
    transition: 'all 0.2s',
    fontSize: 14,
    fontWeight: 500,
  },
};