import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  scrollNav: {
    position: 'fixed',
    right: '40px',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
    zIndex: 1000,
    maxHeight: 'calc(100vh - 200px)',
  },
  dotsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
    overflowY: 'visible',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
  },
  scrollItem: {
    position: 'relative',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollDotContainer: {
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  scrollDot: {
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    background: 'rgba(155, 93, 229, 0.15)',
    border: '2px solid',
    borderColor: 'rgba(155, 93, 229, 0.3)',
    transition: 'all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  scrollDotHover: {
    width: '36px',
    height: '36px',
    background: 'rgba(155, 93, 229, 0.1)',
    borderColor: 'rgba(155, 93, 229, 0.5)',
  },
  scrollDotActiveSystem: {
    width: '36px',
    height: '36px',
    background: theme.colors.secondary,
    borderColor: theme.colors.secondary,
    boxShadow: '0 0 24px rgba(251, 191, 36, 0.4)',
  },
  scrollDotActiveCustom: {
    width: '36px',
    height: '36px',
    background: theme.colors.teal,
    borderColor: theme.colors.teal,
    boxShadow: '0 0 24px rgba(20, 184, 166, 0.4)',
  },
  scrollDotActiveAdd: {
    width: '36px',
    height: '36px',
    background: theme.colors.primary,
    borderColor: theme.colors.primary,
    boxShadow: '0 0 24px rgba(155, 93, 229, 0.4)',
  },
  scrollDotDragOver: {
    width: '40px',
    height: '40px',
    background: 'rgba(155, 93, 229, 0.3)',
    borderColor: theme.colors.primary,
    boxShadow: '0 0 30px rgba(155, 93, 229, 0.6)',
    transform: 'scale(1.1)',
  },
  scrollIcon: {
    position: 'absolute',
    fontSize: '18px',
    opacity: 0,
    transition: 'opacity 0.3s ease, transform 0.3s ease',
    transform: 'scale(0.8)',
  },
  scrollIconVisible: {
    opacity: 1,
    transform: 'scale(1)',
  },
  scrollLine: {
    width: '2px',
    height: '24px',
    background: 'rgba(155, 93, 229, 0.1)',
    marginTop: '4px',
  },
  scrollLabel: {
    position: 'absolute',
    right: '56px',
    top: '0',
    fontSize: '13px',
    fontWeight: 600,
    color: theme.colors.text,
    background: 'rgba(255, 255, 255, 0.98)',
    padding: '8px 14px',
    borderRadius: '10px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    whiteSpace: 'nowrap',
    zIndex: 100000,
    transition: 'all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
    display: 'flex',
    alignItems: 'center',
    height: '40px',
  },
  paginationArrow: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: 'rgba(155, 93, 229, 0.1)',
    border: '2px solid',
    borderColor: 'rgba(155, 93, 229, 0.3)',
    color: theme.colors.primary,
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    flexShrink: 0,
  },
  paginationArrowUp: {
    marginBottom: '8px',
  },
  paginationArrowDown: {
    marginTop: '8px',
  },
  paginationArrowHover: {
    background: 'rgba(155, 93, 229, 0.2)',
    borderColor: theme.colors.primary,
    transform: 'scale(1.1)',
  },
  paginationArrowDisabled: {
    opacity: 0.3,
    cursor: 'not-allowed',
  },
  contextMenu: {
    position: 'fixed',
    background: 'white',
    borderRadius: '10px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
    padding: '8px',
    zIndex: 2000,
    minWidth: '140px',
  },
  contextMenuItem: {
    padding: '10px 16px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '14px',
    fontWeight: 500,
    color: theme.colors.text,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
};