import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  scrollNav: {
    position: 'fixed',
    right: '40px',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
    zIndex: 100,
  },
  scrollItem: {
    position: 'relative',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollDotContainer: {
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  scrollDot: {
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    background: 'rgba(155, 93, 229, 0.15)',
    border: '2px solid',
    borderColor: 'rgba(155, 93, 229, 0.3)',
    transition: 'all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  scrollDotHover: {
    width: '36px',
    height: '36px',
    background: 'rgba(155, 93, 229, 0.1)',
    borderColor: 'rgba(155, 93, 229, 0.5)',
  },
  scrollDotActive: {
    width: '36px',
    height: '36px',
    background: theme.colors.secondary,
    borderColor: theme.colors.secondary,
    boxShadow: '0 0 24px rgba(251, 191, 36, 0.4)',
  },
  scrollIcon: {
    position: 'absolute',
    fontSize: '18px',
    opacity: 0,
    transition: 'opacity 0.3s ease, transform 0.3s ease',
    transform: 'scale(0.8)',
  },
  scrollIconVisible: {
    opacity: 1,
    transform: 'scale(1)',
  },
  scrollLine: {
    position: 'absolute',
    top: '40px',
    left: '50%',
    width: '2px',
    height: '32px',
    background: 'rgba(155, 93, 229, 0.1)',
    transform: 'translateX(-50%)',
  },
  scrollLabel: {
    position: 'absolute',
    right: '56px',
    top: '50%',
    transform: 'translateY(-50%) translateX(-8px)',
    fontSize: '13px',
    fontWeight: 600,
    color: theme.colors.text,
    background: 'rgba(255, 255, 255, 0.98)',
    padding: '8px 14px',
    borderRadius: '10px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    whiteSpace: 'nowrap',
    animation: 'fadeIn 0.3s ease',
  },
};