import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  listHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    marginBottom: '24px',
  },
  listIcon: {
    fontSize: '48px',
    flexShrink: 0,
  },
  listIconEditable: {
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    border: '3px solid transparent',
    padding: '8px',
    borderRadius: '12px',
    background: 'transparent',
  },
  listIconHover: {
    background: 'rgba(251, 191, 36, 0.25)',
    borderColor: '#fbbf24',
    transform: 'scale(1.1)',
    boxShadow: '0 4px 12px rgba(251, 191, 36, 0.4)',
  },
  listIconFocused: {
    borderColor: '#9b5de5',
    background: 'rgba(155, 93, 229, 0.1)',
  },
  listIconFocusedHover: {
    background: 'rgba(251, 191, 36, 0.25)',
    borderColor: '#fbbf24',
    transform: 'scale(1.1)',
    boxShadow: '0 4px 12px rgba(251, 191, 36, 0.4)',
  },
  listTitleGroup: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  listTitle: {
    fontSize: '28px',
    fontWeight: 700,
    color: theme.colors.text,
    margin: 0,
  },
  listTitleEditable: {
    fontSize: '28px',
    fontWeight: 700,
    color: theme.colors.text,
    background: 'transparent',
    border: '2px solid transparent',
    padding: '6px 10px',
    borderRadius: '10px',
    outline: 'none',
    maxWidth: '550px',
    transition: 'all 0.2s',
  },
  listSubtitle: {
    fontSize: '15px',
    fontWeight: 500,
    color: theme.colors.muted,
    margin: 0,
  },
  brandGradient: {
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  listDeleteBtn: {
    marginLeft: 0,
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    background: 'rgba(155, 93, 229, 0.1)',
    border: '1px solid rgba(155, 93, 229, 0.2)',
    color: theme.colors.primary,
    fontSize: '20px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'none',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    flexShrink: 0,
    padding: 0,
    alignSelf: 'center',
    lineHeight: 1,
    paddingBottom: '3px',
  },
  listDeleteBtnVisible: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listDeleteBtnHover: {
    background: '#ef4444',
    borderColor: '#dc2626',
    color: 'white',
    transform: 'scale(1.08)',
    boxShadow: '0 2px 8px rgba(239, 68, 68, 0.3)',
  },
  listTitleEditableFocus: {
    background: 'white',
    borderColor: theme.colors.primary,
    boxShadow: '0 0 0 3px rgba(155, 93, 229, 0.1)',
  },
  listTitleContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  listContainer: {
    position: 'relative',
    overflow: 'visible',
    height: '100%',
    width: '100%',
  },
  listScrollWrapper: {
    display: 'flex',
    gap: '20px',
    overflowX: 'auto',
    overflowY: 'visible',
    padding: '16px 8px',
    scrollBehavior: 'smooth',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    alignItems: 'flex-start',
  },
  scrollArrow: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '48px',
    height: '120px',
    background: 'rgba(0, 0, 0, 0.15)',
    backdropFilter: 'blur(10px)',
    border: 'none',
    color: 'white',
    fontSize: '36px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
    visibility: 'hidden',
    transition: 'opacity 0.3s ease, background 0.2s ease',
    zIndex: 10,
    borderRadius: '8px',
  },
  scrollArrowVisible: {
    visibility: 'visible',
    opacity: 1,
  },
  scrollArrowHover: {
    opacity: '1 !important' as any,
    background: 'rgba(0, 0, 0, 0.25)',
  },
  scrollArrowLeft: {
    left: '8px',
  },
  scrollArrowRight: {
    right: '8px',
  },
};