import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  container: {
    background: 'white',
    borderRadius: '16px',
    padding: '16px',
    boxShadow: theme.shadows.md,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    height: '720px',
    overflow: 'hidden',
    marginBottom: "60px",
  },
  grid: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
  },
  headerRow: {
    display: 'grid',
    gridTemplateColumns: '80px repeat(4, 1fr)',
    gap: '1px',
    background: 'rgba(107, 114, 128, 0.1)',
    borderRadius: '12px 12px 0 0',
    overflow: 'hidden',
    marginBottom: '1px',
  },
  timeHeader: {
    background: 'white',
    padding: '12px 8px',
    fontWeight: 600,
    fontSize: '14px',
    color: theme.colors.muted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayHeader: {
    background: 'white',
    padding: '12px 8px',
    textAlign: 'center',
    fontWeight: 600,
    transition: 'all 0.2s',
  },
  dayHeaderToday: {
    background: 'rgba(155, 93, 229, 0.1)',
    borderBottom: `3px solid ${theme.colors.primary}`,
    color: theme.colors.primary,
  },
  dayName: {
    fontSize: '12px',
    color: theme.colors.muted,
    marginBottom: '4px',
  },
  dayDate: {
    fontSize: '14px',
    color: theme.colors.text,
  },
  bodyContainer: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  timeRow: {
    display: 'grid',
    gridTemplateColumns: '80px repeat(4, 1fr)',
    gap: '1px',
    background: 'rgba(107, 114, 128, 0.1)',
    minHeight: '60px',
  },
  timeLabel: {
    background: 'white',
    padding: '8px',
    fontSize: '12px',
    fontWeight: 500,
    color: theme.colors.muted,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderTop: '1px solid rgba(107, 114, 128, 0.1)',
  },
  dayCell: {
    background: 'white',
    padding: '4px',
    position: 'relative',
    minHeight: '60px',
    maxHeight: '60px',
    borderTop: '1px solid rgba(107, 114, 128, 0.1)',
    borderRight: '1px solid rgba(107, 114, 128, 0.1)',
    borderBottom: '1px solid transparent',
    borderLeft: '1px solid transparent',
    transition: 'all 0.2s',
    cursor: 'pointer',
    overflow: 'visible',
  },
  dayCellPast: {
    background: theme.colors.bg,
    cursor: 'default',
  },
  dayCellToday: {
    background: 'rgba(155, 93, 229, 0.05)',
    borderLeft: `2px solid ${theme.colors.primary}`,
    borderRight: `2px solid ${theme.colors.primary}`,
    borderTop: '1px solid rgba(107, 114, 128, 0.1)',
    borderBottom: '1px solid transparent',
  },
  dayCellHover: {
    background: 'rgba(155, 93, 229, 0.02)',
    borderTop: '1px dashed rgba(155, 93, 229, 0.4)',
    borderRight: '1px dashed rgba(155, 93, 229, 0.4)',
    borderBottom: '1px dashed rgba(155, 93, 229, 0.4)',
    borderLeft: '1px dashed rgba(155, 93, 229, 0.4)',
  },
  dayCellTodayHover: {
    background: 'rgba(155, 93, 229, 0.08)',
    borderLeft: `2px solid ${theme.colors.primary}`,
    borderRight: `2px solid ${theme.colors.primary}`,
    borderTop: '1px dashed rgba(155, 93, 229, 0.4)',
    borderBottom: '1px dashed rgba(155, 93, 229, 0.4)',
  },
  postContainer: {
    display: 'flex',
    gap: '4px',
    height: '100%',
  },
  overflowIndicator: {
    position: 'absolute',
    bottom: '4px',
    right: '6px',
    background: 'rgba(155, 93, 229, 0.1)',
    color: theme.colors.primary,
    border: '1px solid rgba(155, 93, 229, 0.3)',
    borderRadius: '10px',
    padding: '1px 6px',
    fontSize: '9px',
    fontWeight: 600,
  },
  timeIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: '3px',
    display: 'flex',
    alignItems: 'center',
    pointerEvents: 'none',
    zIndex: 10,
  },
  timeIndicatorDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: '#d32f2f',
    border: '2px solid white',
    position: 'absolute',
    left: '-5px',
    zIndex: 11,
    boxShadow: '0 2px 4px rgba(211, 47, 47, 0.4)',
  },
  timeIndicatorLine: {
    width: '100%',
    height: '3px',
    background: '#d32f2f',
    boxShadow: '0 1px 3px rgba(211, 47, 47, 0.3)',
  },
  post: {
    background: theme.colors.surface,
    borderRadius: '6px',
    padding: '4px 6px',
    fontSize: '10px',
    boxShadow: theme.shadows.sm,
    cursor: 'pointer',
    transition: 'all 0.2s',
    borderLeft: `3px solid ${theme.colors.primary}`,
    height: '100%',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  postHalf: {
    width: 'calc(50% - 2px)',
  },
  postHovered: {
    transform: 'translateX(2px)',
    boxShadow: '0 2px 6px rgba(155, 93, 229, 0.15)',
  },
  postHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginBottom: '2px',
  },
  postLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    minWidth: 0,
  },
  postRight: {
    marginLeft: 'auto',
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
  },
  statusIndicator: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    flexShrink: 0,
    cursor: 'pointer',
  },
  statusSuccess: {
    background: theme.colors.teal,
  },
  statusFailed: {
    background: theme.colors.pink,
  },
  statusScheduled: {
    background: 'transparent',
    border: `1px solid ${theme.colors.text}`,
  },
  statusTooltip: {
    position: 'absolute',
    bottom: '12px',
    left: '50%',
    transform: 'translateX(-50%)',
    background: theme.colors.text,
    color: 'white',
    padding: '4px 8px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    pointerEvents: 'none',
    zIndex: 1000,
  },
  postTime: {
    fontWeight: 600,
    color: theme.colors.text,
    whiteSpace: 'nowrap',
    fontSize: '9px',
  },
  mediaIcon: {
    fontSize: '10px',
  },
  postTitle: {
    fontWeight: 700,
    color: theme.colors.text,
    fontSize: '10px',
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  platformIcon: {
    width: '16px',
    height: '16px',
    objectFit: 'contain',
  },
  badge: {
    width: '14px',
    height: '14px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '2px',
    fontWeight: 900,
    fontSize: '8px',
    color: 'white',
    boxShadow: '0 1px 2px rgba(0,0,0,0.2)',
    letterSpacing: '0.2px',
  },
  badgeYt: {
    background: '#ff0033',
  },
  badgeIg: {
    background: theme.gradients.vibe,
  },
  badgeTt: {
    background: theme.colors.text,
  },
  badgeFb: {
    background: theme.colors.blue,
  },
};