import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  chatContainer: {
    flex: 1,
    background: 'rgba(255, 255, 255, 0.8)',
    border: '2px solid rgba(155, 93, 229, 0.1)',
    borderRadius: '20px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    position: 'relative',
    direction: 'rtl',
    transition: 'all 0.6s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  chatContainerInitial: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: '24px',
    padding: '40px 24px',
    textAlign: 'center',
  },
  chatContainerExpanded: {
    transform: 'scale(1.02)',
    boxShadow: '0 20px 40px rgba(155, 93, 229, 0.15)',
  },
  initialTitle: {
    fontSize: '32px',
    fontWeight: 700,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    margin: 0,
    // Removed display: 'inline-block' to match demo
  },
  initialChatInputArea: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    width: '100%',
    direction: 'rtl',
    maxWidth: 'none', // This ensures full width like in demo
  },
  chatHeader: {
    padding: '24px',
    textAlign: 'center',
    borderBottom: '1px solid rgba(155, 93, 229, 0.1)',
    background: 'rgba(255, 255, 255, 0.9)',
    display: 'none', // Hidden by default, shown when expanded
  },
  chatMessages: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  message: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
    animation: 'fadeInUp 0.4s ease',
    direction: 'rtl',
  },
  messageAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    flexShrink: 0,
  },
  messageAvatarAgent: {
    background: theme.gradients.innovator,
    color: '#fff',
    fontWeight: 700,
    fontSize: '16px',
  },
  messageAvatarUser: {
    background: 'rgba(155, 93, 229, 0.1)',
  },
  messageContent: {
    flex: 1,
    textAlign: 'right',
  },
  messageText: {
    fontSize: '14px',
    lineHeight: 1.6,
    color: theme.colors.text,
    marginBottom: '12px',
    direction: 'rtl',
  },
  loadingDots: {
    display: 'inline-flex',
    gap: '4px',
    alignItems: 'center',
    marginRight: '8px',
  },
  ideasList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '8px',
  },
  chatInputArea: {
    padding: '20px',
    background: 'rgba(255, 255, 255, 0.95)',
    borderTop: '1px solid rgba(155, 93, 229, 0.1)',
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    direction: 'rtl',
  },
  chatInput: {
    flex: 1,
    padding: '16px 24px',
    border: 'none',
    borderRadius: '25px',
    fontSize: '14px',
    outline: 'none',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    background: 'rgba(249, 250, 251, 0.8)',
    backdropFilter: 'blur(10px)',
    textAlign: 'right',
    direction: 'rtl',
    boxShadow: 'inset 0 1px 3px rgba(0, 0, 0, 0.08)',
  },
  chatInputFocus: {
    background: 'rgba(255, 255, 255, 0.95)',
    boxShadow: 'inset 0 1px 3px rgba(0, 0, 0, 0.08), 0 0 0 3px rgba(155, 93, 229, 0.1)',
    transform: 'translateY(-1px)',
  },
  chatSendBtn: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    background: 'rgba(155, 93, 229, 0.08)',
    border: '2px solid rgba(155, 93, 229, 0.15)',
    color: theme.colors.primary,
    fontSize: '20px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  chatSendBtnHover: {
    transform: 'scale(1.05)',
    background: 'rgba(155, 93, 229, 0.12)',
    borderColor: 'rgba(155, 93, 229, 0.25)',
  },
};