import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

type S = Record<string, CSSProperties>;

export const styles: S = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    padding: '20px 0',
  },
  emailInfo: {
    textAlign: 'center',
    padding: '20px',
    background: theme.colors.primaryLight,
    borderRadius: '12px',
    border: `1px solid rgba(155, 93, 229, 0.2)`,
  },
  icon: {
    fontSize: '48px',
    marginBottom: '12px',
  },
  emailText: {
    fontSize: '14px',
    color: theme.colors.muted,
    margin: '0 0 8px 0',
  },
  emailAddress: {
    fontSize: '16px',
    fontWeight: 600,
    color: theme.colors.text,
    margin: 0,
  },
  instructions: {
    textAlign: 'center',
  },
  instructionText: {
    fontSize: '15px',
    color: theme.colors.text,
    lineHeight: 1.6,
    margin: '0 0 12px 0',
  },
  note: {
    fontSize: '13px',
    color: theme.colors.muted,
    margin: '0 0 12px 0',
  },
  autoDetectNote: {
    fontSize: '13px',
    color: theme.colors.primary,
    fontWeight: 600,
    margin: 0,
    padding: '8px',
    background: 'rgba(155, 93, 229, 0.05)',
    borderRadius: '8px',
    display: 'inline-block',
  },
  successNotice: {
    background: 'rgba(20, 184, 166, 0.1)',
    color: theme.colors.teal,
    border: '1px solid rgba(20, 184, 166, 0.3)',
    borderRadius: '12px',
    padding: '12px 16px',
    fontSize: '14px',
    fontWeight: 500,
    textAlign: 'center',
  },
  errorNotice: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#dc2626',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '12px',
    padding: '12px 16px',
    fontSize: '14px',
    textAlign: 'center',
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '8px',
  },
  primaryButton: {
    height: '44px',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
    color: '#fff',
    backgroundImage: theme.gradients.innovator,
    boxShadow: theme.shadows.primary,
    fontSize: '14px',
    fontWeight: 600,
    transition: 'transform 0.2s, box-shadow 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButton: {
    height: '44px',
    border: `2px solid ${theme.colors.primary}`,
    borderRadius: '12px',
    cursor: 'pointer',
    color: theme.colors.primary,
    background: 'transparent',
    fontSize: '14px',
    fontWeight: 600,
    transition: 'all 0.2s',
  },
  textButton: {
    height: '40px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: theme.colors.muted,
    fontSize: '14px',
    fontWeight: 500,
    transition: 'color 0.2s',
  },
};