import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(4px)',
    zIndex: 3000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal: {
    width: '95%',
    maxWidth: '900px',
    maxHeight: '85vh',
    background: 'white',
    borderRadius: '16px',
    border: `2px solid ${theme.colors.primary}`,
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.1), 0 0 22px 6px var(--color-primary)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    animation: 'fadeInUp 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  modalHeader: {
    padding: '24px 28px',
    borderBottom: '1px solid rgba(155, 93, 229, 0.1)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.03) 0%, rgba(251, 191, 36, 0.03) 100%)',
  },
  modalTitleGroup: {
    flex: 1,
  },
  modalSubtitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: theme.colors.muted,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    marginBottom: '6px',
  },
  modalTitle: {
    fontSize: '28px',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    margin: 0,
  },
  closeBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    background: 'rgba(155, 93, 229, 0.08)',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '18px',
    color: theme.colors.muted,
  },
  closeBtnHover: {
    background: 'rgba(155, 93, 229, 0.15)',
    transform: 'rotate(90deg)',
  },
  modalBody: {
    flex: 1,
    padding: '28px',
    overflowY: 'auto',
    display: 'grid',
    gridTemplateColumns: '1.618fr 1fr',
    gap: '32px',
  },
  leftColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  rightColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  label: {
    fontSize: '14px',
    fontWeight: 700,
    color: theme.colors.text,
  },
  textarea: {
    width: '100%',
    minHeight: '120px',
    padding: '14px',
    border: '2px solid rgba(155, 93, 229, 0.15)',
    borderRadius: '12px',
    background: 'rgba(249, 250, 251, 0.5)',
    fontSize: '14px',
    lineHeight: 1.6,
    resize: 'vertical',
    transition: 'all 0.2s',
    color: theme.colors.text,
    fontFamily: 'inherit',
    outline: 'none',
  },
  textareaError: {
    borderColor: '#ef4444',
    animation: 'shake 0.3s ease',
  },
  helper: {
    fontSize: '12px',
    color: theme.colors.muted,
  },
  themeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
  },
  themeOption: {
    position: 'relative',
    borderRadius: '10px',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    border: '3px solid transparent',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
  },
  themeOptionHover: {
    transform: 'translateY(-3px)',
    boxShadow: '0 6px 16px rgba(0, 0, 0, 0.12)',
    borderColor: theme.colors.primary,
  },
  themeOptionSelected: {
    borderColor: theme.colors.secondary,
    boxShadow: '0 0 0 4px rgba(251, 191, 36, 0.25)',
  },
  themeOptionError: {
    borderColor: '#ef4444',
    animation: 'shake 0.3s ease',
  },
  themeThumbnail: {
    aspectRatio: '9/16',
    width: '100%',
    position: 'relative',
  },
  themeName: {
    position: 'absolute',
    bottom: '6px',
    left: '6px',
    right: '6px',
    background: 'rgba(255, 255, 255, 0.95)',
    padding: '5px 8px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 600,
    textAlign: 'center',
    color: theme.colors.text,
  },
  logoSelector: {
    display: 'flex',
    gap: '10px',
  },
  logoOption: {
    width: '72px',
    height: '72px',
    border: '2px solid rgba(155, 93, 229, 0.15)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s',
    background: 'rgba(249, 250, 251, 0.5)',
    position: 'relative',
    flexDirection: 'column',
    gap: '4px',
    padding: '8px',
  },
  logoOptionHover: {
    borderColor: theme.colors.primary,
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 12px rgba(155, 93, 229, 0.15)',
  },
  logoOptionSelected: {
    borderColor: theme.colors.secondary,
    background: 'rgba(251, 191, 36, 0.05)',
    boxShadow: '0 0 0 4px rgba(251, 191, 36, 0.25)',
  },
  logoIcon: {
    fontSize: '28px',
  },
  logoText: {
    fontSize: '9px',
    fontWeight: 600,
    textAlign: 'center',
    color: theme.colors.text,
  },
  logoSaved: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    background: theme.colors.secondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '22px',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    boxShadow: '0 2px 8px rgba(251, 191, 36, 0.2)',
  },
  logoAdd: {
    color: theme.colors.teal,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
  },
  logoAddText: {
    fontSize: '8px',
    fontWeight: 600,
    color: theme.colors.muted,
  },
  soundGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '8px',
    gridAutoRows: 'minmax(70px, auto)',
  },
  soundOption: {
    border: '2px solid rgba(155, 93, 229, 0.15)',
    borderRadius: '8px',
    padding: '10px 6px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    background: 'rgba(249, 250, 251, 0.5)',
    position: 'relative',
    minHeight: '70px',
  },
  soundOptionHover: {
    borderColor: theme.colors.primary,
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 12px rgba(155, 93, 229, 0.15)',
  },
  soundOptionSelected: {
    borderColor: theme.colors.secondary,
    background: 'rgba(251, 191, 36, 0.05)',
    boxShadow: '0 0 0 4px rgba(251, 191, 36, 0.25)',
  },
  soundIcon: {
    fontSize: '18px',
    color: theme.colors.primary,
  },
  soundName: {
    fontSize: '9px',
    fontWeight: 600,
    textAlign: 'center',
    color: theme.colors.text,
  },
  soundFavorite: {
    position: 'absolute',
    top: '2px',
    right: '2px',
    fontSize: '10px',
    color: theme.colors.pink,
  },
  libraryBtn: {
    padding: '10px 20px',
    borderRadius: '10px',
    fontWeight: 600,
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    background: 'transparent',
    color: theme.colors.primary,
    border: `2px solid ${theme.colors.primary}`,
    marginTop: '8px',
  },
  libraryBtnHover: {
    background: 'rgba(155, 93, 229, 0.08)',
    transform: 'translateY(-1px)',
  },
  modalFooter: {
    padding: '20px 28px',
    borderTop: '1px solid rgba(155, 93, 229, 0.1)',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    background: 'rgba(249, 250, 251, 0.5)',
  },
  generateBtn: {
    padding: '18px 24px',
    background: 'linear-gradient(135deg, var(--color-primary) 0%, var(--color-secondary) 100%)',
    border: 'none',
    borderRadius: '14px',
    color: 'white',
    fontWeight: 700,
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 6px 20px rgba(155, 93, 229, 0.3), 0 3px 10px rgba(251, 191, 36, 0.25)',
    position: 'relative',
    overflow: 'hidden',
    letterSpacing: '0.5px',
  },
  generateBtnHover: {
    transform: 'translateY(-4px) scale(1.02)',
    boxShadow: '0 12px 35px rgba(155, 93, 229, 0.5), 0 8px 20px rgba(251, 191, 36, 0.4), 0 0 30px rgba(155, 93, 229, 0.3)',
    filter: 'brightness(1.1)',
  },
  generateBtnActive: {
    transform: 'translateY(-2px) scale(0.98)',
  },
  confirmOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(4px)',
    zIndex: 3001,
  },
  confirmDialog: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    background: 'white',
    borderRadius: '16px',
    padding: '28px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.2)',
    zIndex: 3002,
    maxWidth: '400px',
    textAlign: 'center',
  },
  confirmTitle: {
    fontSize: '18px',
    fontWeight: 700,
    marginBottom: '16px',
    color: theme.colors.text,
  },
  confirmMessage: {
    fontSize: '14px',
    lineHeight: 1.6,
    color: theme.colors.muted,
    marginBottom: '24px',
    whiteSpace: 'pre-line',
  },
  creditsBold: {
    fontWeight: 700,
    color: theme.colors.text,
  },
  confirmButtons: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'center',
  },
  confirmBtn: {
    padding: '12px 24px',
    borderRadius: '10px',
    fontWeight: 600,
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    border: 'none',
  },
  confirmBtnCancel: {
    background: 'rgba(107, 114, 128, 0.1)',
    color: theme.colors.muted,
  },
  confirmBtnCancelHover: {
    background: 'rgba(107, 114, 128, 0.15)',
  },
  confirmBtnProceed: {
    background: theme.gradients.innovator,
    color: 'white',
    boxShadow: '0 4px 12px rgba(155, 93, 229, 0.3)',
  },
  confirmBtnProceedHover: {
    transform: 'translateY(-1px)',
    boxShadow: '0 6px 20px rgba(155, 93, 229, 0.4)',
  },
  celebrationContainer: {
    position: 'fixed',
    inset: 0,
    zIndex: 3005,
    pointerEvents: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  celebrationContent: {
    textAlign: 'center',
    animation: 'celebrationPulse 2s ease-out',
  },
  celebrationIcon: {
    fontSize: '80px',
    marginBottom: '20px',
  },
  celebrationText: {
    fontSize: '32px',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  confetti: {
    position: 'absolute',
    width: '10px',
    height: '10px',
    background: theme.colors.secondary,
    animation: 'confettiFall 3s ease-out forwards',
  },
};