import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  container: {
    position: 'relative',
  },
  selector: {
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(255,255,255,0.9)',
    border: '2px solid',
    borderColor: theme.colors.secondary,
    borderRadius: '16px',
    padding: '8px 16px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4,0,0.2,1)',
    userSelect: 'none',
    whiteSpace: 'nowrap',
    width: '225px',
    outline: 'none !important',
    boxShadow: 'none !important',
  },
  tenantName: {
    fontWeight: 600,
    color: theme.colors.text,
    fontSize: '15px',
    flex: 1,
    textAlign: 'left',
  },
  brandIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    background: theme.colors.secondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    border: '2px solid',
    borderColor: 'rgba(255,255,255,0.3)',
    boxShadow: '0 2px 8px rgba(251, 191, 36, 0.2)',
    flexShrink: 0,
    marginLeft: '12px',
  },
  dropdown: {
    position: 'absolute',
    top: 'calc(100% + 10px)',
    left: 0,
    width: '225px',
    background: 'rgba(255,255,255,0.98)',
    border: '1px solid',
    borderColor: theme.colors.secondary,
    borderRadius: '12px',
    padding: '6px',
    boxShadow: '0 10px 25px rgba(251, 191, 36, 0.15)',
    zIndex: 2000,
  },
  option: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    padding: '10px 12px',
    border: '0px solid',
    borderColor: 'transparent',
    background: 'transparent',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    color: theme.colors.text,
    fontSize: '14px',
    transition: 'all 0.2s ease',
    outline: 'none !important',
    boxShadow: 'none !important',
  },
  optionActive: {
    background: 'rgba(251, 191, 36, 0.2)',
    color: '#d97706',
  },
  optIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    borderRadius: '8px',
    background: 'rgba(155, 93, 229, 0.08)',
    fontSize: '18px',
  },
  addBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: 500,
    color: theme.colors.muted,
    borderTop: '1px solid rgba(251, 191, 36, 0.2)',
    marginTop: '4px',
    border: '0px solid',
    borderColor: 'transparent',
    background: 'transparent',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    outline: 'none !important',
    boxShadow: 'none !important',
  },
  addIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '24px',
    fontSize: '14px',
    background: 'rgba(20, 184, 166, 0.1)',
    borderRadius: '8px',
  },
  logoImage: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    borderRadius: '8px',
  },
};