import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  // ... (Keep existing styles) ...
  nav: {
      background: 'rgba(255,255,255,0.95)',
      backdropFilter: 'blur(20px)',
      borderBottom: '1px solid rgba(155, 93, 229, 0.1)',
      padding: '12px 24px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      position: 'sticky',
      top: 0,
      zIndex: 1000,
      boxShadow: theme.shadows.primary,
    },
    navLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '32px',
    },
    logo: {
      fontSize: '24px',
      fontWeight: 800,
      background: theme.gradients.innovator,
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      backgroundClip: 'text',
      textDecoration: 'none',
      letterSpacing: '-0.5px',
      cursor: 'pointer',
    },
    navCenter: {
      display: 'flex',
      gap: '8px',
      background: 'transparent',
      padding: '4px',
      borderRadius: '12px',
    },
    navItemWrapper: {
      position: 'relative',
      display: 'inline-flex',
      alignItems: 'center',
    },
    navBtn: {
      padding: '12px 20px',
      border: 'none',
      borderRadius: '10px',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'all 0.2s',
      textDecoration: 'none',
      color: theme.colors.muted,
      background: 'transparent',
      fontSize: '14px',
    },
    navBtnActive: {
      background: theme.gradients.momentum,
      color: '#fff',
      boxShadow: '0 4px 12px rgba(155, 93, 229, 0.3)',
    },
    navRight: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    navIcon: {
      width: '44px',
      height: '44px',
      border: 'none',
      borderRadius: '50%',
      background: 'rgba(155, 93, 229, 0.08)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      transition: 'all 0.2s',
      fontSize: '20px',
      color: theme.colors.muted,
    },
    secondaryNav: {
      background: 'rgba(255, 255, 255, 0.92)',
      backdropFilter: 'blur(15px)',
      borderBottom: '1px solid rgba(155, 93, 229, 0.06)',
      padding: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      top: 'calc(100% + 5px)',
      left: '50%',
      transform: 'translateX(-50%)',
      zIndex: 999,
      boxShadow: 'none',
      height: 0,
      overflow: 'hidden',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      borderRadius: 0,
      whiteSpace: 'nowrap',
      minWidth: '300px',
    },
    secondaryNavVisible: {
      height: '60px',
      padding: '8px 24px',
      boxShadow: '0 2px 15px rgba(155, 93, 229, 0.05)',
      borderRadius: '0 0 16px 16px',
    },
    secondaryNavItems: {
      display: 'inline-flex',
      gap: '6px',
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnSub: {
      padding: '10px 18px',
      fontSize: '13px',
      border: 'none',
      borderRadius: '10px',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'all 0.2s',
      textDecoration: 'none',
      color: theme.colors.muted,
      background: 'transparent',
    },
    btnSubHover: {
      color: theme.colors.primary,
      background: 'rgba(155, 93, 229, 0.08)',
    },
    btnSubActive: {
      background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.6) 0%, rgba(59, 130, 246, 0.6) 100%)',
      color: '#fff',
      boxShadow: '0 3px 10px rgba(155, 93, 229, 0.25)',
    },

  // New Styles
  userName: {
    fontSize: '14px',
    fontWeight: 600,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginRight: '8px',
  },
  logoutBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    border: '1px solid transparent',
    background: 'transparent',
    color: theme.colors.muted,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
};