import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  nav: {
    background: 'rgba(255,255,255,0.95)',
    backdropFilter: 'blur(20px)',
    borderBottom: '1px solid',
    borderColor: 'rgba(155, 93, 229, 0.1)',
    padding: '12px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: theme.shadows.primary,
  },
  navLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '32px',
  },
  logo: {
    fontSize: '24px',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    textDecoration: 'none',
    letterSpacing: '-0.5px',
    cursor: 'pointer',
  },
  navCenter: {
    display: 'flex',
    gap: '8px',
    background: 'transparent',
    padding: '4px',
    borderRadius: '12px',
  },
  navItemWrapper: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
  },
  navBtn: {
    padding: '12px 20px',
    border: 'none',
    borderColor: 'transparent',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    textDecoration: 'none',
    color: theme.colors.muted,
    background: 'transparent',
    fontSize: '14px',
  },
  navBtnActive: {
    background: theme.gradients.momentum,
    color: '#fff',
    boxShadow: '0 4px 12px rgba(155, 93, 229, 0.3)',
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  secondaryNav: {
    background: 'rgba(255, 255, 255, 0.92)',
    backdropFilter: 'blur(15px)',
    borderBottom: '1px solid',
    borderColor: 'rgba(155, 93, 229, 0.06)',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 'calc(100% + 5px)',
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 999,
    boxShadow: 'none',
    height: 0,
    overflow: 'hidden',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    borderRadius: 0,
    whiteSpace: 'nowrap',
    minWidth: '300px',
  },
  secondaryNavVisible: {
    height: '60px',
    padding: '8px 24px',
    boxShadow: '0 2px 15px rgba(155, 93, 229, 0.05)',
    borderRadius: '0 0 16px 16px',
  },
  secondaryNavItems: {
    display: 'inline-flex',
    gap: '6px',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnSub: {
    padding: '10px 18px',
    fontSize: '13px',
    border: 'none',
    borderColor: 'transparent',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    textDecoration: 'none',
    color: theme.colors.muted,
    background: 'transparent',
  },
  btnSubHover: {
    color: theme.colors.primary,
    background: 'rgba(155, 93, 229, 0.08)',
  },
  btnSubActive: {
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.6) 0%, rgba(59, 130, 246, 0.6) 100%)',
    color: '#fff',
    boxShadow: '0 3px 10px rgba(155, 93, 229, 0.25)',
  },
  // Unified Icon Button Style
  iconBtn: {
    width: '44px',
    height: '44px',
    border: 'none',
    borderColor: 'transparent',
    borderRadius: '50%',
    background: 'transparent', // Default transparent
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    fontSize: '20px',
    color: theme.colors.muted,
  },
  // Active/Hover states for Icon Buttons
  iconBtnHover: {
    background: 'rgba(155, 93, 229, 0.08)',
    transform: 'translateY(-1px)',
    color: theme.colors.primary,
  },
  // Specific style for Logout (Danger)
  iconBtnDangerHover: {
    background: '#fee2e2',
    color: '#ef4444',
    transform: 'translateY(-1px)',
    boxShadow: '0 2px 4px rgba(239, 68, 68, 0.1)',
  },
  // Avatar Circle
  avatar: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    fontWeight: 700,
    color: '#fff',
    border: '2px solid rgba(255, 255, 255, 0.8)',
    boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
    textTransform: 'uppercase',
  },
  comingSoonBadge: {
    position: 'absolute',
    bottom: 'calc(100% - 2px)',
    left: '50%',
    transform: 'translateX(-50%)',
    padding: '3px 10px',
    fontSize: '9px',
    fontWeight: 700,
    borderRadius: '6px',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: '#fff',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    boxShadow: '0 3px 8px rgba(59, 130, 246, 0.35)',
    whiteSpace: 'nowrap',
    transition: 'opacity 0.3s ease, transform 0.3s ease',
    pointerEvents: 'none',
    border: 'none',
  },
};