import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.75)',
    backdropFilter: 'blur(8px)',
    zIndex: 5000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    animation: 'fadeIn 0.2s ease-out',
  },
  modal: {
    background: 'white',
    borderRadius: '24px',
    overflow: 'hidden',
    boxShadow: '0 25px 80px rgba(0, 0, 0, 0.3)',
    width: '900px', // Strict fixed width
    height: '600px', // Strict fixed height
    position: 'relative',
    animation: 'scaleIn 0.3s ease-out',
  },
  closeBtn: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: 'rgba(255, 255, 255, 0.9)',
    border: 'none',
    borderColor: 'transparent',
    color: '#666',
    fontSize: '24px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
    zIndex: 10,
  },
  closeBtnHover: {
    background: 'white',
    transform: 'scale(1.1)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
  },
  content: {
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
  },
  mediaSection: {
    flex: '1 1 60%',
    background: '#000',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '600px', // Static height
    minHeight: '600px',
  },
  media: {
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain',
  },
  mediaPlaceholder: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    background: '#1a1a1a',
    color: '#666',
  },
  infoSection: {
    flex: '1 1 40%',
    padding: '72px 32px 32px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    maxWidth: '360px',
    overflowY: 'auto',
    overflowX: 'hidden',
    height: '600px', // Match media height
  },
  titleSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  title: {
    fontSize: '22px',
    fontWeight: 700,
    color: '#111827',
    margin: 0,
    flex: 1,
    wordBreak: 'break-word',
  },
  renameInput: {
    flex: '1 1 auto',
    width: '100%',
    minWidth: '0',
    maxWidth: '180px',
    fontSize: '20px',
    fontWeight: 600,
    color: '#111827',
    padding: '8px 12px',
    border: '2px solid',
    borderColor: '#9b5de5',
    borderRadius: '8px',
    outline: 'none',
  },
  editBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    background: 'rgba(155, 93, 229, 0.1)',
    border: 'none',
    borderColor: 'transparent',
    fontSize: '16px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
    flexShrink: 0,
  },
  editBtnHover: {
    background: 'rgba(155, 93, 229, 0.2)',
    transform: 'scale(1.1)',
  },
  favoriteBtn: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    background: 'rgba(0, 0, 0, 0.05)',
    backdropFilter: 'blur(10px)',
    border: '2px solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '22px',
    transition: 'all 0.2s ease',
    padding: 0,
    flexShrink: 0,
  },
  favoriteBtnHover: {
    transform: 'scale(1.1)',
    background: 'rgba(0, 0, 0, 0.1)',
    borderColor: 'rgba(0, 0, 0, 0.2)',
  },
  favoriteBtnActive: {
    background: 'rgba(239, 68, 68, 0.15)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  metadata: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '20px',
    background: '#f9fafb',
    borderRadius: '16px',
  },
  metaItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaLabel: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#6b7280',
  },
  metaValue: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#111827',
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: 'auto',
  },
  actionBtn: {
    padding: '14px 20px',
    borderRadius: '12px',
    border: 'none',
    borderColor: 'transparent',
    fontSize: '15px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s',
  },
  downloadBtn: {
    background: '#3b82f6', // Distinct Blue
    color: 'white',
    boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)',
  },
  downloadBtnHover: {
    background: '#2563eb',
    transform: 'translateY(-2px)',
    boxShadow: '0 6px 16px rgba(59, 130, 246, 0.4)',
  },
  deleteBtn: {
    background: 'transparent',
    color: '#ef4444',
    border: '2px solid',
    borderColor: '#ef4444',
  },
  deleteBtnHover: {
    background: '#ef4444',
    color: 'white',
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 12px rgba(239, 68, 68, 0.2)',
  },
};
