import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    backdropFilter: 'blur(8px)',
    zIndex: 5000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    animation: 'fadeIn 0.2s ease-out',
  },
  modal: {
    backgroundColor: 'white',
    width: '900px',
    maxWidth: '95vw',
    height: '600px',
    maxHeight: '90vh',
    borderRadius: '24px',
    overflow: 'hidden',
    display: 'flex',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    position: 'relative',
  },
  closeBtn: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    border: 'none',
    borderColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#374151',
    zIndex: 10,
    transition: 'background 0.2s',
  },
  // Left Side - Media
  mediaSection: {
    flex: '1.2',
    backgroundColor: '#000',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  mediaElement: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  // Right Side - Metadata
  metaSection: {
    flex: '0.8',
    padding: '32px',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
    overflowY: 'auto',
  },
  title: {
    fontSize: '24px',
    fontWeight: 700,
    color: '#111827',
    marginBottom: '8px',
    lineHeight: 1.3,
  },
  date: {
    fontSize: '14px',
    color: '#6b7280',
    marginBottom: '24px',
  },
  divider: {
    height: '1px',
    backgroundColor: '#e5e7eb',
    margin: '24px 0',
  },
  metaGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px',
  },
  metaItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  metaLabel: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  metaValue: {
    fontSize: '15px',
    color: '#374151',
    fontWeight: 500,
  },
  actions: {
    marginTop: 'auto',
    display: 'flex',
    gap: '12px',
    paddingTop: '24px',
  },
  actionBtn: {
    flex: 1,
    padding: '12px',
    borderRadius: '12px',
    border: '1px solid',
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    color: '#374151',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s',
  },
  primaryBtn: {
    backgroundColor: '#9b5de5',
    borderColor: '#9b5de5',
    color: 'white',
  }
};