import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 40px',
    position: 'relative',
    overflow: 'hidden',
  },
  content: {
    width: '100%',
    maxWidth: '720px',
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '28px',
    padding: '56px 64px',
    boxShadow: '0 24px 64px rgba(155, 93, 229, 0.15)',
    border: '2px solid',
    borderColor: 'rgba(200, 200, 200, 0.3)',
    position: 'relative',
    zIndex: 1,
    animation: 'fadeInUp 0.5s ease-out',
  },
  header: {
    textAlign: 'center',
    marginBottom: '44px',
  },
  title: {
    fontSize: '40px',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    marginBottom: '14px',
    letterSpacing: '-0.5px',
  },
  subtitle: {
    fontSize: '17px',
    color: theme.colors.muted,
    lineHeight: 1.6,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '48px',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '36px',
  },
  errorMessage: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px 20px',
    background: 'rgba(239, 68, 68, 0.08)',
    border: '2px solid',
    borderColor: '#ef4444',
    borderRadius: '14px',
    color: '#ef4444',
    fontSize: '14px',
    fontWeight: 500,
  },
  errorIcon: {
    fontSize: '20px',
  },
  successMessage: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '16px 20px',
    background: 'rgba(20, 184, 166, 0.08)',
    border: '2px solid #14b8a6',
    borderRadius: '14px',
    color: '#14b8a6',
    fontSize: '14px',
    fontWeight: 500,
  },
  successIcon: {
    fontSize: '20px',
  },
  actions: {
    display: 'flex',
    marginTop: '12px',
  },
  submitBtn: {
    flex: 1,
    height: '56px',
    border: 'none',
    borderRadius: '14px',
    background: theme.gradients.innovator,
    color: 'white',
    fontSize: '17px',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 8px 24px rgba(155, 93, 229, 0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    fontFamily: 'inherit',
    position: 'relative',
    overflow: 'hidden',
    transform: 'scale(1)',
  },
  submitBtnHover: {
    transform: 'translateY(-1px)',
    boxShadow: '0 8px 24px rgba(155, 93, 229, 0.3)',
  },
  submitBtnActive: {
    transform: 'translateY(0)',
    boxShadow: '0 4px 12px rgba(155, 93, 229, 0.2)',
  },
  submitBtnLoading: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
  ripple: {
    position: 'absolute',
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    background: 'rgba(255, 255, 255, 0.6)',
    animation: 'ripple 0.6s ease-out',
    pointerEvents: 'none',
  },
  spinner: {
    width: '20px',
    height: '20px',
    border: '3px solid',
    borderColor: 'rgba(255, 255, 255, 0.3)',
    borderTopColor: 'white',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  privacyNote: {
    textAlign: 'center',
    fontSize: '14px',
    color: theme.colors.muted,
    marginTop: '8px',
  },
};