import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  nav: {
    background: 'rgba(255,255,255,0.95)',
    backdropFilter: 'blur(20px)',
    borderBottom: '1px solid rgba(155, 93, 229, 0.1)',
    padding: '12px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: theme.shadows.primary,
  },
  navLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '32px',
  },
  logo: {
    fontSize: '24px',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    textDecoration: 'none',
    letterSpacing: '-0.5px',
  },
  navCenter: {
    display: 'flex',
    gap: '8px',
    background: 'transparent',
    padding: '4px',
    borderRadius: '12px',
  },
  navBtn: {
    padding: '12px 20px',
    border: 'none',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    textDecoration: 'none',
    color: theme.colors.muted,
    background: 'transparent',
    fontSize: '14px',
  },
  navBtnActive: {
    background: theme.gradients.momentum,
    color: '#fff',
    boxShadow: '0 4px 12px rgba(155, 93, 229, 0.3)',
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  navIcon: {
    width: '44px',
    height: '44px',
    border: 'none',
    borderRadius: '50%',
    background: 'rgba(155, 93, 229, 0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '20px',
    color: theme.colors.muted,
  },
};