import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

type S = Record<string, CSSProperties>;

export const styles: S = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: theme.gradients.background,
    padding: '24px',
  },
  card: {
    background: 'white',
    borderRadius: '20px',
    padding: '48px',
    boxShadow: theme.shadows.lg,
    maxWidth: '500px',
    width: '100%',
    textAlign: 'center',
    border: `2px solid ${theme.colors.primary}`,
  },
  spinner: {
    width: '60px',
    height: '60px',
    border: '4px solid rgba(155, 93, 229, 0.2)',
    borderTopColor: theme.colors.primary,
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    margin: '0 auto 24px',
  },
  successIcon: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: theme.gradients.balance,
    color: 'white',
    fontSize: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 24px',
    animation: 'fadeInScale 0.5s ease',
  },
  errorIcon: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
    color: 'white',
    fontSize: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 24px',
    animation: 'fadeInScale 0.5s ease',
  },
  title: {
    fontSize: '28px',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    marginBottom: '12px',
  },
  subtitle: {
    fontSize: '16px',
    color: theme.colors.muted,
    lineHeight: 1.6,
    marginBottom: '24px',
  },
  errorText: {
    fontSize: '15px',
    color: '#ef4444',
    lineHeight: 1.6,
    marginBottom: '24px',
  },
  autoCloseMessage: {
    fontSize: '13px',
    color: theme.colors.muted,
    fontStyle: 'italic',
    marginTop: '16px',
  },
  button: {
    padding: '14px 28px',
    background: theme.gradients.innovator,
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '15px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s',
    boxShadow: theme.shadows.primary,
  },
};