import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

// Purple SVG arrow for dropdowns (same as DatePicker)
const arrowSvg = `url("data:image/svg+xml,%3Csvg width='12' height='8' viewBox='0 0 12 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1.5L6 6.5L11 1.5' stroke='%239B5DE5' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E")`;

export const styles: Record<string, CSSProperties> = {
  container: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    width: '100%',
  },
  label: {
    fontSize: '15px',
    fontWeight: 600,
    color: theme.colors.text,
  },
  inputContainer: {
    display: 'flex',
    alignItems: 'center',
    height: '52px',
    padding: '0 44px 0 16px',
    border: '2px solid',
    borderColor: 'rgba(155, 93, 229, 0.2)',
    borderRadius: '12px',
    background: 'white',
    cursor: 'pointer',
    transition: 'border-color 0.2s',
    width: '100%',
    backgroundImage: arrowSvg,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 16px center',
  },
  inputContainerFocused: {
    borderColor: 'rgba(155, 93, 229, 0.35)',
  },
  selectedValue: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
    gap: '12px',
  },
  countryName: {
    fontSize: '15px',
    color: theme.colors.text,
    fontWeight: 500,
    flex: 1,
  },
  flagImage: {
    width: '24px',
    height: '18px',
    objectFit: 'cover',
    borderRadius: '2px',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
  },
  searchInput: {
    flex: 1,
    border: 'none',
    outline: 'none',
    fontSize: '15px',
    background: 'transparent',
    color: theme.colors.text,
    fontFamily: 'inherit',
    width: '100%',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    position: 'absolute',
    right: '40px',
    top: '50%',
    transform: 'translateY(-50%)',
  },
  clearBtn: {
    width: '20px',
    height: '20px',
    border: 'none',
    background: 'rgba(0, 0, 0, 0.06)',
    borderRadius: '50%',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    color: theme.colors.muted,
    transition: 'background 0.2s',
  },
  dropdown: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    right: 0,
    background: 'white',
    border: '2px solid',
    borderColor: 'rgba(155, 93, 229, 0.15)',
    borderRadius: '12px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12)',
    zIndex: 1000,
    overflow: 'hidden',
    width: '100%',
  },
  dropdownList: {
    maxHeight: '280px',
    overflowY: 'auto',
    padding: '6px 0',
  },
  option: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '12px 16px',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  optionHighlighted: {
    background: 'rgba(155, 93, 229, 0.08)',
  },
  optionSelected: {
    background: 'rgba(155, 93, 229, 0.12)',
  },
  optionName: {
    flex: 1,
    fontSize: '15px',
    color: theme.colors.text,
  },
  optionFlag: {
    width: '24px',
    height: '18px',
    objectFit: 'cover',
    borderRadius: '2px',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
  },
  noResults: {
    padding: '20px',
    textAlign: 'center',
    color: theme.colors.muted,
    fontSize: '14px',
  },
};