import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  // Model Selector
  modelSelector: {
    position: 'relative',
    display: 'inline-block',
  },
  modelButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 18px',
    border: '2px solid rgba(155, 93, 229, 0.2)',
    borderRadius: '12px',
    fontWeight: 550,
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    minWidth: '140px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.15)',
    color: '#111827',
    outline: 'none',
  },
  modelButtonVeo3: {
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.1) 0%, rgba(251, 191, 36, 0.1) 30%, rgba(245, 158, 11, 0.1) 70%, rgba(217, 119, 6, 0.1) 100%)',
  },
  modelButtonVeo2: {
    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.1) 0%, rgba(147, 51, 234, 0.1) 50%, rgba(236, 72, 153, 0.1) 100%)',
  },
  modelButtonOpen: {},
  arrow: {
    marginLeft: 'auto',
    transition: 'transform 0.3s ease',
  },
  arrowOpen: {
    transform: 'rotate(180deg)',
  },
  modelDropdown: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    left: 0,
    width: '360px',
    background: 'rgba(255, 255, 255, 0.98)',
    border: `2px solid ${theme.colors.primary}`,
    borderRadius: '12px',
    padding: '8px',
    boxShadow: '0 15px 35px rgba(155, 93, 229, 0.2)',
    zIndex: 100,
  },
  modelOption: {
    padding: '12px 16px',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    marginBottom: '6px',
    border: '2px solid transparent',
  },
  modelOptionVeo3: {
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.1) 0%, rgba(251, 191, 36, 0.1) 30%, rgba(245, 158, 11, 0.1) 70%, rgba(217, 119, 6, 0.1) 100%)',
    borderColor: 'rgba(251, 191, 36, 0.3)',
  },
  modelOptionVeo2: {
    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.1) 0%, rgba(147, 51, 234, 0.1) 50%, rgba(236, 72, 153, 0.1) 100%)',
  },
  modelOptionSelected: {},
  modelOptionSelectedVeo3: {
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.2) 0%, rgba(251, 191, 36, 0.2) 30%, rgba(245, 158, 11, 0.2) 70%, rgba(217, 119, 6, 0.2) 100%)',
    borderColor: '#fbbf24',
  },
  modelOptionSelectedVeo2: {
    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.2) 0%, rgba(147, 51, 234, 0.2) 50%, rgba(236, 72, 153, 0.2) 100%)',
    borderColor: '#9333ea',
  },
  modelOptionTitle: {
    fontWeight: 700,
    marginBottom: '4px',
    fontSize: '15px',
  },
  modelOptionDesc: {
    fontSize: '13px',
    color: theme.colors.muted,
    lineHeight: 1.4,
    whiteSpace: 'pre-line',
  },

  // Chat Container
  chatContainer: {
    flex: 1,
    background: 'rgba(255, 255, 255, 0.8)',
    border: '2px solid rgba(155, 93, 229, 0.1)',
    borderRadius: '20px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    transition: 'all 0.6s cubic-bezier(0.4, 0, 0.2, 1)',
    direction: 'rtl',
  },
  chatContainerInitial: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: '24px',
    padding: '40px 24px',
    textAlign: 'center',
  },
  chatContainerExpanded: {
    transform: 'scale(1.02)',
    boxShadow: '0 20px 40px rgba(155, 93, 229, 0.15)',
  },
  initialTitle: {
    fontSize: '32px',
    fontWeight: 700,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    margin: 0,
  },
  initialInputArea: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    width: '100%',
    direction: 'rtl',
    maxWidth: 'none',
  },
  chatMessages: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  message: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
    animation: 'fadeInUp 0.4s ease',
    direction: 'rtl',
  },
  messageAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    flexShrink: 0,
    background: 'rgba(155, 93, 229, 0.1)',
  },
  messageAvatarAgent: {
    background: theme.gradients.innovator,
    color: '#fff',
    fontWeight: 700,
    fontSize: '16px',
  },
  messageContent: {
    flex: 1,
    textAlign: 'right',
  },
  messageText: {
    fontSize: '14px',
    lineHeight: 1.6,
    color: theme.colors.text,
    marginBottom: '12px',
    direction: 'rtl',
  },
  loadingDots: {
    display: 'inline-flex',
    gap: '4px',
    alignItems: 'center',
    marginRight: '8px',
  },
  chatInputArea: {
    padding: '20px',
    background: 'rgba(255, 255, 255, 0.95)',
    borderTop: '1px solid rgba(155, 93, 229, 0.1)',
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    direction: 'rtl',
  },
  chatInput: {
    flex: 1,
    padding: '16px 24px',
    border: 'none',
    borderRadius: '25px',
    fontSize: '14px',
    outline: 'none',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    background: 'rgba(249, 250, 251, 0.8)',
    backdropFilter: 'blur(10px)',
    textAlign: 'right',
    direction: 'rtl',
    boxShadow: 'inset 0 1px 3px rgba(0, 0, 0, 0.08)',
  },
  sendBtn: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    background: 'rgba(155, 93, 229, 0.08)',
    border: '2px solid rgba(155, 93, 229, 0.15)',
    color: theme.colors.primary,
    fontSize: '20px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    outline: 'none',
  },

  // Ideas List
  ideasList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '8px',
  },
  ideaCard: {
    background: '#fff',
    border: '2px solid rgba(155, 93, 229, 0.2)',
    borderRadius: '16px',
    padding: '16px 20px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    fontSize: '14px',
    lineHeight: 1.6,
    color: theme.colors.text,
    position: 'relative',
    textAlign: 'right',
    direction: 'rtl',
  },
  ideaCardFocused: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 2001,
    width: '90%',
    maxWidth: '600px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.1), 0 0 22px 6px var(--color-primary)',
    borderColor: theme.colors.primary,
    animation: 'focusAppear 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  ideaText: {},
  ideaTextarea: {
    minHeight: '120px',
    padding: '12px',
    border: '1px solid rgba(155, 93, 229, 0.2)',
    borderRadius: '8px',
    outline: 'none',
    fontSize: '14px',
    lineHeight: 1.6,
    resize: 'none',
    fontFamily: 'inherit',
    textAlign: 'right',
    direction: 'rtl',
    background: '#fff',
    width: '100%',
  },
  previewBtn: {
    position: 'absolute',
    bottom: '28px',
    left: '28px',
    padding: '10px 20px',
    borderRadius: '12px',
    background: 'rgba(255, 255, 255, 0.95)',
    border: '1px solid rgba(20, 184, 166, 0.2)',
    color: '#6b7280',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.3s ease',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
    backdropFilter: 'blur(10px)',
    outline: 'none',
  },
  loadingSpinner: {
    display: 'inline-flex',
    gap: '4px',
    marginLeft: '12px',
  },
  focusOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(4px)',
    zIndex: 2000,
    transition: 'opacity 0.3s ease',
  },

  // Detailed View
  detailedCard: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 2001,
    maxWidth: '900px',
    width: '95%',
    maxHeight: '85vh',
    overflowY: 'auto',
    padding: 0,
    background: '#fff',
    border: `2px solid ${theme.colors.primary}`,
    borderRadius: '16px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.1), 0 0 22px 6px var(--color-primary)',
    animation: 'expandToDetail 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  detailedContent: {
    display: 'flex',
    height: '100%',
    flexDirection: 'row',
  },
  detailedSidebar: {
    width: '280px',
    padding: '24px',
    background: 'rgba(249, 250, 251, 0.5)',
    borderLeft: '1px solid rgba(155, 93, 229, 0.1)',
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    justifyContent: 'space-between',
  },
  sidebarTopGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  detailedMain: {
    flex: 1,
    padding: '28px',
    overflowY: 'auto',
  },
  detailedHeader: {
    marginBottom: '20px',
  },
  fieldLabel: {
    fontSize: '11px',
    fontWeight: 500,
    color: theme.colors.muted,
    marginBottom: '4px',
    textAlign: 'left',
    direction: 'ltr',
    fontFamily: 'inherit',
  },
  detailedTitle: {
    width: '100%',
    padding: '6px 8px',
    border: '1px solid rgba(155, 93, 229, 0.15)',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 400,
    background: 'rgba(249, 250, 251, 0.5)',
    textAlign: 'left',
    direction: 'ltr',
    outline: 'none',
    transition: 'all 0.2s',
    marginBottom: '6px',
  },
  detailedDescription: {
    width: '100%',
    padding: '6px 8px',
    border: '1px solid rgba(155, 93, 229, 0.15)',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 400,
    background: 'rgba(249, 250, 251, 0.5)',
    textAlign: 'left',
    direction: 'ltr',
    outline: 'none',
    transition: 'all 0.2s',
    minHeight: '45px',
    resize: 'none',
    fontFamily: 'inherit',
  },
  detailedSeparator: {
    height: '1px',
    background: 'linear-gradient(90deg, transparent, rgba(155, 93, 229, 0.2), transparent)',
    margin: '20px 0',
  },
  detailedPrompt: {
    padding: '20px',
    background: 'rgba(155, 93, 229, 0.05)',
    borderRadius: '12px',
    border: '1px solid rgba(155, 93, 229, 0.1)',
  },
  detailedPromptTitle: {
    fontWeight: 700,
    color: theme.colors.primary,
    marginBottom: '12px',
    fontSize: '16px',
    textAlign: 'left',
    direction: 'ltr',
  },
  detailedPromptText: {
    fontSize: '15px',
    lineHeight: 1.7,
    color: theme.colors.text,
    textAlign: 'left',
    direction: 'ltr',
    whiteSpace: 'pre-wrap',
    padding: '16px',
    border: '2px solid rgba(155, 93, 229, 0.2)',
    borderRadius: '10px',
    minHeight: '100px',
    background: '#fff',
    transition: 'all 0.2s',
    outline: 'none',
  },
  modelDisplay: {
    padding: '10px 14px',
    borderRadius: '10px',
    border: '2px solid transparent',
    fontWeight: 600,
    fontSize: '13px',
    textAlign: 'center',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    overflow: 'hidden',
  },
  modelDisplayVeo3: {
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.25) 0%, rgba(251, 191, 36, 0.25) 30%, rgba(245, 158, 11, 0.25) 70%, rgba(217, 119, 6, 0.25) 100%)',
    borderColor: 'rgba(251, 191, 36, 0.3)',
    color: theme.colors.text,
  },
  modelDisplayVeo2: {
    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.13) 0%, rgba(147, 51, 234, 0.13) 50%, rgba(236, 72, 153, 0.13) 100%)',
    color: theme.colors.text,
  },
  priceDisplay: {
    padding: '20px',
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.03), rgba(251, 191, 36, 0.03))',
    borderRadius: '12px',
    border: '1px solid rgba(155, 93, 229, 0.1)',
    textAlign: 'center',
  },
  priceLabel: {
    fontSize: '11px',
    color: theme.colors.muted,
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  priceValue: {
    fontSize: '28px',
    fontWeight: 700,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  priceUnit: {
    fontSize: '14px',
    color: theme.colors.muted,
    fontWeight: 400,
    marginLeft: '4px',
  },
  generateBtn: {
    padding: '18px 24px',
    background: 'linear-gradient(135deg, var(--color-primary) 0%, var(--color-secondary) 100%)',
    border: 'none',
    borderRadius: '14px',
    color: 'white',
    fontWeight: 700,
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 6px 20px rgba(155, 93, 229, 0.3), 0 3px 10px rgba(251, 191, 36, 0.25)',
    position: 'relative',
    overflow: 'hidden',
    letterSpacing: '0.5px',
    direction: 'ltr',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    marginTop: 'auto',
    outline: 'none',
  },
  generateBtnIcon: {
    fontSize: '20px',
    filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.2))',
  },

  // Confirmation Dialog
  confirmDialog: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    background: 'white',
    borderRadius: '16px',
    padding: '28px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.2)',
    zIndex: 3000,
    maxWidth: '400px',
    textAlign: 'center',
  },
  confirmTitle: {
    fontSize: '18px',
    fontWeight: 700,
    marginBottom: '16px',
    color: theme.colors.text,
  },
  confirmMessage: {
    fontSize: '14px',
    lineHeight: 1.6,
    color: theme.colors.muted,
    marginBottom: '24px',
    whiteSpace: 'pre-line',
  },
  confirmButtons: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'center',
  },
  confirmBtn: {
    padding: '12px 24px',
    borderRadius: '10px',
    fontWeight: 600,
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    border: 'none',
    outline: 'none',
  },
  confirmBtnCancel: {
    background: 'rgba(107, 114, 128, 0.1)',
    color: theme.colors.muted,
  },
  confirmBtnProceed: {
    background: theme.gradients.innovator,
    color: 'white',
    boxShadow: '0 4px 12px rgba(155, 93, 229, 0.3)',
  },

  // Celebration Animation
  celebrationContainer: {
    position: 'fixed',
    inset: 0,
    zIndex: 4000,
    pointerEvents: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  celebrationContent: {
    textAlign: 'center',
    animation: 'celebrationPulse 2s ease-out',
  },
  celebrationIcon: {
    fontSize: '80px',
    marginBottom: '20px',
  },
  celebrationText: {
    fontSize: '32px',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  confetti: {
    position: 'absolute',
    width: '10px',
    height: '10px',
    background: theme.colors.secondary,
    animation: 'confettiFall 3s ease-out forwards',
  },
};