import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  ideaCard: {
    background: '#fff',
    border: '2px solid rgba(155, 93, 229, 0.2)',
    borderColor: 'rgba(155, 93, 229, 0.2)',
    borderRadius: '16px',
    padding: '16px 20px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    fontSize: '14px',
    lineHeight: 1.6,
    color: theme.colors.text,
    position: 'relative',
    textAlign: 'left',
    direction: 'ltr',
  },
  ideaCardHover: {
    transform: 'translateY(-4px)',
    boxShadow: '0 12px 25px rgba(155, 93, 229, 0.15)',
    borderColor: theme.colors.primary,
  },
  ideaText: {
    display: 'block',
  },
  focusOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(4px)',
    zIndex: 2000,
    opacity: 1,
    pointerEvents: 'auto',
    transition: 'opacity 0.3s ease',
  },
  ideaCardFocused: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 2001,
    width: '90%',
    maxWidth: '600px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.1), 0 0 22px 6px var(--color-primary)',
    borderColor: theme.colors.primary,
    background: '#fff',
    padding: '16px 20px',
    animation: 'focusAppear 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    borderRadius: '16px',
    border: `2px solid ${theme.colors.primary}`,
  },
  ideaTextArea: {
    minHeight: '120px',
    padding: '12px',
    border: '1px solid rgba(155, 93, 229, 0.2)',
    borderRadius: '8px',
    outline: 'none',
    fontSize: '14px',
    lineHeight: 1.6,
    resize: 'none',
    fontFamily: 'inherit',
    textAlign: 'left',
    direction: 'ltr',
    background: '#fff',
    width: '100%',
  },
  ideaPreviewBtn: {
    position: 'absolute',
    bottom: '28px',
    left: '28px',
    padding: '10px 20px',
    borderRadius: '12px',
    background: 'rgba(255, 255, 255, 0.95)',
    border: '1px solid rgba(20, 184, 166, 0.2)',
    color: theme.colors.muted,
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.3s ease',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
    backdropFilter: 'blur(10px)',
    outline: 'none', // Remove outline
  },
  ideaPreviewBtnHover: {
    background: 'rgba(20, 184, 166, 0.05)',
    color: theme.colors.muted,
    borderColor: theme.colors.teal,
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 12px rgba(20, 184, 166, 0.1)',
  },
  loadingSpinner: {
    display: 'inline-flex',
    gap: '4px',
    marginLeft: '12px',
  },
  ideaCardDetailed: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 3000,
    maxWidth: '900px',
    width: '95%',
    maxHeight: '85vh',
    overflowY: 'auto',
    padding: 0,
    background: '#fff',
    border: `2px solid ${theme.colors.primary}`,
    borderRadius: '16px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.1), 0 0 22px 6px var(--color-primary)',
    animation: 'expandToDetail 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  detailedContent: {
    display: 'flex',
    height: '100%',
    flexDirection: 'row',
  },
  detailedSidebar: {
    width: '280px',
    padding: '24px',
    background: 'rgba(249, 250, 251, 0.5)',
    borderLeft: '1px solid rgba(155, 93, 229, 0.1)',
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    justifyContent: 'space-between',
  },
  sidebarTopGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  detailedMain: {
    flex: 1,
    padding: '28px',
    overflowY: 'auto',
  },
  detailedHeader: {
    marginBottom: '20px',
  },
  fieldLabel: {
    fontSize: '11px',
    fontWeight: 500,
    color: theme.colors.muted,
    marginBottom: '4px',
    textAlign: 'left',
    direction: 'ltr',
    fontFamily: 'inherit',
  },
  detailedTitle: {
    width: '100%',
    padding: '6px 8px',
    border: '1px solid rgba(155, 93, 229, 0.15)',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 400,
    background: 'rgba(249, 250, 251, 0.5)',
    textAlign: 'left',
    direction: 'ltr',
    outline: 'none',
    transition: 'all 0.2s',
    marginBottom: '6px',
    minHeight: 'auto',
  },
  detailedDescription: {
    width: '100%',
    padding: '6px 8px',
    border: '1px solid rgba(155, 93, 229, 0.15)',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 400,
    background: 'rgba(249, 250, 251, 0.5)',
    textAlign: 'left',
    direction: 'ltr',
    outline: 'none',
    transition: 'all 0.2s',
    minHeight: '45px',
    resize: 'none',
    fontFamily: 'inherit',
  },
  detailedSeparator: {
    height: '1px',
    background: 'linear-gradient(90deg, transparent, rgba(155, 93, 229, 0.2), transparent)',
    margin: '20px 0',
  },
  detailedPrompt: {
    padding: '20px',
    background: 'rgba(155, 93, 229, 0.05)',
    borderRadius: '12px',
    border: '1px solid rgba(155, 93, 229, 0.1)',
    position: 'relative',
  },
  detailedPromptTitle: {
    fontWeight: 700,
    color: theme.colors.primary,
    marginBottom: '12px',
    fontSize: '16px',
    textAlign: 'left',
    direction: 'ltr',
  },
  detailedPromptText: {
    fontSize: '15px',
    lineHeight: 1.7,
    color: theme.colors.text,
    textAlign: 'left',
    direction: 'ltr',
    whiteSpace: 'pre-wrap',
    padding: '16px',
    border: '2px solid rgba(155, 93, 229, 0.2)',
    borderRadius: '10px',
    minHeight: '100px',
    background: '#fff',
    transition: 'all 0.2s',
    outline: 'none',
  },
  modelDisplay: {
    padding: '10px 14px',
    borderRadius: '10px',
    border: '2px solid transparent',
    fontWeight: 600,
    fontSize: '13px',
    textAlign: 'center',
    cursor: 'default',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    overflow: 'hidden',
  },
  modelDisplayVeo3: {
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.25) 0%, rgba(251, 191, 36, 0.25) 30%, rgba(245, 158, 11, 0.25) 70%, rgba(217, 119, 6, 0.25) 100%)',
    borderColor: 'rgba(251, 191, 36, 0.3)',
    color: theme.colors.text,
  },
  modelDisplayVeo2: {
    background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.13) 0%, rgba(147, 51, 234, 0.13) 50%, rgba(236, 72, 153, 0.13) 100%)',
    color: theme.colors.text,
  },
  priceDisplay: {
    padding: '20px',
    background: 'linear-gradient(135deg, rgba(155, 93, 229, 0.03), rgba(251, 191, 36, 0.03))',
    borderRadius: '12px',
    border: '1px solid rgba(155, 93, 229, 0.1)',
    textAlign: 'center',
  },
  priceLabel: {
    fontSize: '11px',
    color: theme.colors.muted,
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  priceValue: {
    fontSize: '28px',
    fontWeight: 700,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  priceUnit: {
    fontSize: '14px',
    color: theme.colors.muted,
    fontWeight: 400,
    marginLeft: '4px',
  },
  loadingDotsContainer: {
    position: 'absolute',
    bottom: '38px',
    right: '38px',
    alignItems: 'center',
    gap: '4px',
  },
};