import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

type S = Record<string, CSSProperties>;

export const styles: S = {
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  primaryBtn: {
    height: 44,
    border: 'none',
    borderRadius: 12,
    cursor: 'pointer',
    color: '#fff',
    backgroundImage: theme.gradients.innovator,
    boxShadow: theme.shadows.primary,
    transition: 'transform 0.2s, box-shadow 0.2s',
    fontSize: 15,
    fontWeight: 600,
    marginTop: 8,
  },
  cancelBtn: {
    height: 40,
    border: '2px solid',
    borderColor: 'rgba(155, 93, 229, 0.2)',
    borderRadius: 12,
    cursor: 'pointer',
    color: theme.colors.muted,
    background: 'transparent',
    transition: 'all 0.2s',
    fontSize: 14,
    fontWeight: 500,
  },
  error: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#ef4444',
    border: '1px solid',
    borderColor: 'rgba(239, 68, 68, 0.3)',
    borderRadius: 12,
    padding: '10px 14px',
    fontSize: 14,
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 20,
    padding: '40px 20px',
  },
  spinner: {
    width: 48,
    height: 48,
    border: '4px solid',
    borderColor: 'rgba(155, 93, 229, 0.2)',
    borderTopColor: theme.colors.primary,
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  loadingText: {
    fontSize: 15,
    color: theme.colors.muted,
    margin: 0,
  },
  errorContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 20,
    padding: '20px',
    textAlign: 'center',
  },
  errorIcon: {
    width: 70,
    height: 70,
    borderRadius: '50%',
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#ef4444',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 40,
    fontWeight: 'bold',
    border: '3px solid',
    borderColor: '#ef4444',
  },
  errorText: {
    fontSize: 15,
    fontWeight: 500,
    color: '#ef4444',
    margin: 0,
    lineHeight: 1.6,
  },
};