import { CSSProperties } from 'react';
// import { theme } from '@/theme/theme'; // Removed direct theme import to use CSS variables instead

export const styles: Record<string, CSSProperties> = {
    toggleRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-start',
        padding: '4px 0',
    },
    toggleLabel: {
        width: '210px',
        flexShrink: 0,
        fontSize: '13px',
        fontWeight: 500,
        color: 'var(--color-text)',
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
    },
    toggleSwitch: {
        position: 'relative',
        width: '42px',
        height: '24px',
        background: '#c4c9d4',
        borderRadius: '12px',
        cursor: 'pointer',
        transition: 'background .25s',
        flexShrink: 0,
        boxShadow: 'inset 0 1px 3px rgba(0,0,0,.15)',
    },
    toggleSwitchOn: {
        background: 'var(--color-primary)',
        boxShadow: 'inset 0 1px 3px rgba(0,0,0,.1)',
    },
    toggleThumb: {
        position: 'absolute',
        top: '3px',
        left: '3px',
        width: '18px',
        height: '18px',
        background: '#fff',
        borderRadius: '50%',
        transition: 'transform .25s cubic-bezier(.4,0,.2,1)',
        boxShadow: '0 1px 4px rgba(0,0,0,.25)',
    },
    tooltipIcon: {
        width: '15px',
        height: '15px',
        borderRadius: '50%',
        background: 'rgba(var(--color-primary-rgb, 155, 93, 229), .1)',
        fontSize: '9px',
        fontWeight: 700,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'var(--color-primary)',
        cursor: 'help',
        flexShrink: 0,
        fontStyle: 'italic',
    },
};
