import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  container: {
    height: '100%',
    overflowY: 'auto',
    overflowX: 'hidden',
    scrollSnapType: 'y proximity',
    scrollBehavior: 'smooth',
    WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(155, 93, 229, 0.3) transparent',
    msOverflowStyle: 'auto',
    scrollPaddingTop: '0px',
    scrollPaddingBottom: '0px',
  },
  creatorSlide: {
    height: 'calc(100vh - 76px)',
    minHeight: '600px',
    scrollSnapAlign: 'center', // Changed from 'start' to 'center' for better centering
    scrollSnapStop: 'normal', // Allows smoother scrolling through multiple sections
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 100px 60px 80px',
    position: 'relative',
  },
  slideShowTime: {},
  slideMatrix: {},
  slideNotes: {},
  slidePicasso: {},
  creatorContent: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    gap: '80px',
    alignItems: 'center',
    maxWidth: '1400px',
    width: '100%',
    margin: '0 auto',
  },
  previewContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewDisplay: {
    width: '280px',
    height: 'calc(280px * 16 / 9)',
    borderRadius: '28px',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 25px 60px rgba(0, 0, 0, 0.15)',
    transform: 'translateY(0)',
    transition: 'all 0.6s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  previewDisplayActive: {
    transform: 'translateY(-10px) scale(1.02)',
    boxShadow: '0 35px 70px rgba(0, 0, 0, 0.2)',
  },
  previewShowTime: {
    background: 'linear-gradient(135deg, #dea86bff 0%, #b5762eff 100%)',
  },
  previewMatrix: {
    background: 'linear-gradient(135deg, #25c99f 0%, #0b8b6e 100%)',
  },
  previewNotes: {
    background: 'linear-gradient(135deg, #ff8ec6 0%, #df4790 100%)',
  },
  previewPicasso: {
    background: 'linear-gradient(135deg, #6f9cff 0%, #3356f7 100%)',
  },
  previewLabel: {
    position: 'absolute',
    top: '20px',
    left: '20px',
    background: 'rgba(255, 255, 255, 0.95)',
    padding: '10px 16px',
    borderRadius: '10px',
    fontSize: '12px',
    fontWeight: 600,
    color: theme.colors.text,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    backdropFilter: 'blur(10px)',
  },
  previewDot: {
    width: '8px',
    height: '8px',
    background: theme.colors.teal,
    borderRadius: '50%',
    boxShadow: '0 0 8px rgba(20, 184, 166, 0.6)',
    animation: 'pulse 2s infinite',
  },
  creatorDetails: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  creatorSubtitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: theme.colors.muted,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
  },
  creatorTitle: {
    fontSize: 'clamp(3rem, 5vw, 4rem)',
    fontWeight: 800,
    background: theme.gradients.innovator,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    letterSpacing: '-1.5px',
    lineHeight: 1,
    margin: 0,
  },
  creatorDescription: {
    fontSize: '17px',
    lineHeight: 1.7,
    color: theme.colors.muted,
    maxWidth: '600px',
    margin: 0,
  },
  creatorMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap',
  },
  pill: {
    padding: '10px 18px',
    borderRadius: '999px',
    fontSize: '14px',
    fontWeight: 600,
    border: '2px solid',
    borderColor: 'transparent',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },
  pillTypeVideo: {
    background: 'rgba(59, 130, 246, 0.1)',
    color: theme.colors.blue,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  pillTypeImage: {
    background: 'rgba(251, 191, 36, 0.1)',
    color: '#d97706',
    borderColor: 'rgba(251, 191, 36, 0.3)',
  },
  pillCredits: {
    background: 'rgba(20, 184, 166, 0.1)',
    color: theme.colors.teal,
    borderColor: 'rgba(20, 184, 166, 0.3)',
  },
  creatorActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '18px',
  },
  btnPrimary: {
    padding: '16px 32px',
    borderRadius: '14px',
    fontWeight: 700,
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '0px solid',
    borderColor: 'transparent',
    background: theme.gradients.innovator,
    color: 'white',
    boxShadow: '0 8px 24px rgba(155, 93, 229, 0.3)',
  },
  btnPrimaryHover: {
    transform: 'translateY(-3px)',
    boxShadow: '0 12px 32px rgba(155, 93, 229, 0.4)',
  },
  btnSecondary: {
    padding: '16px 32px',
    borderRadius: '14px',
    fontWeight: 700,
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px solid',

    background: 'transparent',
    color: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  btnSecondaryHover: {
    background: 'rgba(155, 93, 229, 0.08)',
    transform: 'translateY(-2px)',
  },
};