import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  calendarGrid: {
    background: 'white',
    borderRadius: '16px',
    padding: '16px',
    boxShadow: theme.shadows.md,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    marginBottom: "60px",
    height: '720px',
  },
  calendarHeader: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '1px',
    marginBottom: '1px',
    background: theme.colors.surface,
    borderRadius: '12px 12px 0 0',
    overflow: 'hidden',
  },
  dayHeader: {
    padding: '10px',
    textAlign: 'center',
    fontWeight: 600,
    color: '#4b5563',
    background: 'white',
    fontSize: '14px',
  },
  calendarBody: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '1px',
    background: theme.colors.surface,
    flex: 1,
    gridTemplateRows: 'repeat(5, 1fr)',
  },
  calendarDay: {
    background: 'white',
    padding: '8px',
    position: 'relative',
    transition: 'all 0.2s',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    minHeight: '100px',
    border: '1px solid',
    borderColor: 'transparent',
  },
  calendarDayOtherMonth: {
    background: 'rgba(245, 245, 250, 0.6)',
  },
  calendarDayPast: {
    background: 'rgba(249, 250, 251, 0.5)',
  },
  calendarDayToday: {
    background: 'rgba(155, 93, 229, 0.05)',
    border: '2px solid',
    borderColor: 'rgba(155, 93, 229, 0.2)',
  },
  calendarDayHover: {
    background: 'rgba(155, 93, 229, 0.02)',
    border: '1px dashed',
    borderColor: 'rgba(155, 93, 229, 0.4)',
  },
  calendarDayDragOver: {
    background: 'rgba(155, 93, 229, 0.1)',
    border: '2px dashed',
    borderColor: 'rgba(155, 93, 229, 0.6)',
  },
  dayNumber: {
    fontSize: '14px',
    fontWeight: 600,
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: '6px',
  },
  dayNumberToday: {
    fontSize: '14px',
    fontWeight: 600,
    color: theme.colors.primary,
    textAlign: 'center',
    marginBottom: '6px',
  },
  dayNumberOtherMonth: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#c0c0c8',
    textAlign: 'center',
    marginBottom: '4px',
  },
  monthLabel: {
    display: 'block',
    fontSize: '10px',
    fontWeight: 500,
    color: '#b0b0bc',
    textAlign: 'center',
    letterSpacing: '0.02em',
    marginTop: '1px',
    lineHeight: 1.2,
  },
  overflowIndicator: {
    position: 'absolute',
    bottom: '4px',
    right: '6px',
    background: 'rgba(155, 93, 229, 0.1)',
    color: theme.colors.primary,
    border: '1px solid',
    borderColor: 'rgba(155, 93, 229, 0.3)',
    borderRadius: '10px',
    padding: '1px 6px',
    fontSize: '9px',
    fontWeight: 600,
  },
  postItem: {
    background: theme.colors.surface,
    borderRadius: '6px',
    padding: '6px 8px',
    marginBottom: '4px',
    fontSize: '11px',
    boxShadow: theme.shadows.sm,
    cursor: 'pointer',
    transition: 'all 0.2s',
    minWidth: 0,
    borderLeft: '3px solid transparent',
  },
  postFirstLine: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '3px',
  },
  postLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
  },
  postRight: {
    marginLeft: 'auto',
    display: 'flex',
    gap: '3px',
    alignItems: 'center',
  },
  statusIndicator: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    flexShrink: 0,
    cursor: 'pointer',
  },
  statusSuccess: {
    background: '#22c55e',
  },
  statusFailed: {
    background: '#ef4444',
  },
  statusScheduled: {
    background: 'white',
    border: '1.7px solid black',
    boxSizing: 'border-box',
  },
  statusDraft: {
    background: 'white',
    border: '2.2px dotted #4b5563',
    boxSizing: 'border-box',
  },
  blackTooltip: {
    position: 'absolute',
    top: '-30px',
    transform: 'translateX(-37%)',
    background: '#333',
    color: 'white',
    padding: '4px 8px',
    borderRadius: '6px',
    fontSize: '12px',
    whiteSpace: 'nowrap',
    zIndex: 1000,
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.2)',
    pointerEvents: 'none',
    transition: 'opacity 0.15s ease, transform 0.15s ease',
  },
  postTime: {
    fontWeight: 600,
    color: theme.colors.text,
    whiteSpace: 'nowrap',
  },
  mediaIcon: {
    fontSize: '12px',
  },
  postTitle: {
    fontWeight: 700,
    color: theme.colors.text,
    fontSize: '11px',
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  platformIcon: {
    width: '14px',
    height: '14px',
    objectFit: 'contain',
  },
  badge: {
    width: '14px',
    height: '14px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '2px',
    fontWeight: 900,
    fontSize: '8px',
    color: 'white',
    boxShadow: '0 1px 2px rgba(0,0,0,0.2)',
    letterSpacing: '0.1px',
  },
  badgeYt: {
    background: '#ff0033',
  },
  badgeIg: {
    background: theme.gradients.vibe,
  },
  badgeTt: {
    background: theme.colors.text,
  },
  badgeFb: {
    background: theme.colors.blue,
  },
};