import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  calendarGrid: {
    background: 'white',
    borderRadius: '16px',
    padding: '16px',
    boxShadow: theme.shadows.md,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    marginBottom: "60px",
    height: '720px',
  },
  calendarHeader: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '1px',
    marginBottom: '1px',
    background: theme.colors.surface,
    borderRadius: '12px 12px 0 0',
    overflow: 'hidden',
  },
  dayHeader: {
    padding: '10px',
    textAlign: 'center',
    fontWeight: 600,
    color: '#4b5563',
    background: 'white',
    fontSize: '14px',
  },
  calendarBody: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '1px',
    background: theme.colors.surface,
    flex: 1,
    gridTemplateRows: 'repeat(5, 1fr)',
  },
  calendarDay: {
    background: 'white',
    padding: '8px',
    position: 'relative',
    transition: 'all 0.2s',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    minHeight: '100px',
    border: '1px solid transparent',
  },
  calendarDayPast: {
    background: `repeating-linear-gradient(
      -45deg,
      ${theme.colors.surface},
      ${theme.colors.bg} 8px,
      hsla(221, 13%, 66%, 0.06) 8px,
      hsla(221, 13%, 66%, 0.06) 16px
    )`,
  },
  calendarDayToday: {
    background: 'rgba(155, 93, 229, 0.05)',
    border: '2px solid rgba(155, 93, 229, 0.2)',
  },
  calendarDayHover: {
    background: 'rgba(155, 93, 229, 0.02)',
    border: '1px dashed rgba(155, 93, 229, 0.4)',
  },
  calendarDayDragOver: {
    background: 'rgba(155, 93, 229, 0.1)',
    border: '2px dashed rgba(155, 93, 229, 0.6)',
  },
  dayNumber: {
    fontSize: '14px',
    fontWeight: 600,
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: '6px',
  },
  dayNumberToday: {
    fontSize: '14px',
    fontWeight: 600,
    color: theme.colors.primary,
    textAlign: 'center',
    marginBottom: '6px',
  },
  overflowIndicator: {
    position: 'absolute',
    bottom: '4px',
    right: '6px',
    background: 'rgba(155, 93, 229, 0.1)',
    color: theme.colors.primary,
    border: '1px solid rgba(155, 93, 229, 0.3)',
    borderRadius: '10px',
    padding: '1px 6px',
    fontSize: '9px',
    fontWeight: 600,
  },
  postItem: {
    background: theme.colors.surface,
    borderRadius: '6px',
    padding: '6px 8px',
    marginBottom: '4px',
    fontSize: '11px',
    boxShadow: theme.shadows.sm,
    cursor: 'pointer',
    transition: 'all 0.2s',
    minWidth: 0,
    borderLeft: '3px solid transparent',
  },
  postFirstLine: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '3px',
  },
  postLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
  },
  postRight: {
    marginLeft: 'auto',
    display: 'flex',
    gap: '3px',
    alignItems: 'center',
  },
  statusIndicator: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    flexShrink: 0,
    cursor: 'pointer',
  },
  statusSuccess: {
    background: theme.colors.teal,
  },
  statusFailed: {
    background: theme.colors.pink,
  },
  statusScheduled: {
    background: 'transparent',
    border: `1px solid ${theme.colors.text}`,
  },
  statusTooltip: {
    position: 'absolute',
    bottom: '16px',
    left: '50%',
    transform: 'translateX(-50%)',
    background: theme.colors.text,
    color: 'white',
    padding: '4px 8px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    pointerEvents: 'none',
    zIndex: 1000,
  },
  postTime: {
    fontWeight: 600,
    color: theme.colors.text,
    whiteSpace: 'nowrap',
  },
  mediaIcon: {
    fontSize: '12px',
  },
  postTitle: {
    fontWeight: 700,
    color: theme.colors.text,
    fontSize: '11px',
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  platformIcon: {
    width: '14px',
    height: '14px',
    objectFit: 'contain',
  },
  badge: {
    width: '14px',
    height: '14px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '2px',
    fontWeight: 900,
    fontSize: '8px',
    color: 'white',
    boxShadow: '0 1px 2px rgba(0,0,0,0.2)',
    letterSpacing: '0.1px',
  },
  badgeYt: {
    background: '#ff0033',
  },
  badgeIg: {
    background: theme.gradients.vibe,
  },
  badgeTt: {
    background: theme.colors.text,
  },
  badgeFb: {
    background: theme.colors.blue,
  },
};