import { CSSProperties } from 'react';
// import { theme } from '@/theme/theme'; // Removed direct theme import to use CSS variables instead

export const styles: Record<string, CSSProperties> = {
    overlay: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(17, 24, 39, 0.25)',
        backdropFilter: 'blur(3px)',
        zIndex: 1500,
    },
    modal: {
        position: 'fixed',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: 1600,
        background: 'var(--color-surface)',
        borderRadius: '16px',
        boxShadow: '0 20px 60px rgba(0, 0, 0, .15), 0 0 0 1px var(--color-bg)',
        maxWidth: '94vw',
        maxHeight: '88vh',
        minHeight: '520px',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '18px 28px',
        background: 'var(--color-bg)',
        borderRadius: '16px 16px 0 0',
        borderBottom: '1px solid var(--color-bg)',
        flexShrink: 0,
    },
    typeLabel: {
        fontSize: '28px',
        lineHeight: 1,
    },
    title: {
        fontSize: '22px',
        fontWeight: 700,
        color: 'var(--color-text)',
    },
    closeBtn: {
        width: '32px',
        height: '32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        border: 'none',
        borderRadius: '50%',
        background: 'rgba(var(--color-text-rgb, 0, 0, 0), .06)',
        color: 'var(--color-muted)',
        fontSize: '18px',
        cursor: 'pointer',
        transition: 'all .2s',
    },
    body: {
        display: 'flex',
        gap: '24px',
        padding: '24px 28px',
        flex: 1,
        overflowY: 'auto',
    },
    leftColumn: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '28px',
    },
    rightColumn: {
        flexShrink: 0,
        width: '240px',
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
    },
    footer: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '16px 28px',
        background: 'var(--color-bg)',
        borderTop: '1px solid var(--color-bg)',
        borderRadius: '0 0 16px 16px',
        flexShrink: 0,
    },
    scrollableBody: {
        flex: 1,
        overflowY: 'auto',
        overflowX: 'hidden',
        scrollbarGutter: 'stable' as const,
    },
};
