import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  contentArea: {
    height: '100%',
    overflowY: 'auto',
    overflowX: 'hidden',
    scrollSnapType: 'y proximity',
    scrollBehavior: 'smooth',
    WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(155, 93, 229, 0.3) transparent',
    msOverflowStyle: 'auto',
    paddingRight: '100px',
  },
  listSection: {
    height: '100%',
    scrollSnapAlign: 'center',
    scrollSnapStop: 'normal',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 24px',
  },
  listWrapper: {
    width: '100%',
    maxWidth: '1600px',
  },
  addListButtonContainer: {
    marginTop: '48px',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  addListButtonHover: {
    background: 'rgba(0, 0, 0, 0.08)',
    borderColor: 'rgba(0, 0, 0, 0.25)',
    opacity: 1,
    transform: 'translateY(-2px)',
  },
  addListButtonWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    padding: '0 24px',
    margin: '32px 0', 
  },
  addListButton: {
    width: '100%',
    maxWidth: '90%', 
    padding: '24px', 
    background: 'rgba(0, 0, 0, 0.05)',
    border: '2px dashed rgba(0, 0, 0, 0.15)',
    borderRadius: '12px',
    color: theme.colors.muted,
    fontWeight: 500,
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    opacity: 0.6,
  },
  fixedAddButton: {
    position: 'fixed',
    bottom: '32px',
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 999,
    padding: '0 24px',
  },
};