import { CSSProperties } from 'react';
// import { theme } from '@/theme/theme'; // Removed direct theme import to use CSS variables instead

export const styles: Record<string, CSSProperties> = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100vw',
        height: '100vh',
        background: 'rgba(0, 0, 0, 0.4)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 5000,
        backdropFilter: 'blur(3px)',
        animation: 'confirmDialogFadeIn 0.2s',
    },
    dialog: {
        background: 'var(--color-surface)',
        borderRadius: '16px',
        width: '400px',
        maxWidth: '90vw',
        padding: '24px',
        boxShadow: '0 10px 40px rgba(0, 0, 0, 0.2)',
        display: 'flex',
        flexDirection: 'column',
    },
    title: {
        fontSize: '18px',
        fontWeight: 600,
        color: 'var(--color-text)',
        margin: '0 0 20px 0',
    },
    row: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        marginBottom: '16px',
    },
    label: {
        fontSize: '14px',
        fontWeight: 500,
        color: 'var(--color-muted)',
        width: '75px',
        flexShrink: 0,
    },
    inputNumber: {
        width: '60px',
        height: '38px',
        padding: '0 12px',
        borderRadius: '8px',
        border: '1px solid var(--color-bg)',
        textAlign: 'center',
        fontSize: '14px',
        fontFamily: 'inherit',
        outline: 'none',
        background: 'var(--color-bg)',
        transition: 'border-color 0.2s',
        boxSizing: 'border-box',
    },
    select: {
        height: '38px',
        padding: '0 32px 0 12px',
        borderRadius: '8px',
        border: '1px solid var(--color-bg)',
        fontSize: '14px',
        fontFamily: 'inherit',
        background: `var(--color-bg) url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%239e9e9e%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E') no-repeat right 12px top 50%`,
        backgroundSize: '10px auto',
        WebkitAppearance: 'none',
        MozAppearance: 'none',
        appearance: 'none',
        outline: 'none',
        flex: 1,
        transition: 'border-color 0.2s',
        boxSizing: 'border-box',
        color: 'var(--color-text)',
    },
    dayBubbles: {
        display: 'flex',
        gap: '6px',
        marginTop: '8px',
    },
    dayBubble: {
        width: '32px',
        height: '32px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '12px',
        fontWeight: 600,
        cursor: 'pointer',
        border: 'none',
        transition: 'all 0.15s',
    },
    endsSection: {
        marginTop: '8px',
    },
    endsLabel: {
        fontSize: '14px',
        fontWeight: 600,
        color: 'var(--color-text)',
        marginBottom: '16px',
        display: 'block',
    },
    radioRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '16px',
    },
    radioLabel: {
        fontSize: '14px',
        color: 'var(--color-text)',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        cursor: 'pointer',
    },
    actions: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '12px',
        marginTop: '24px',
    },
    cancelBtn: {
        padding: '0 16px',
        height: '38px',
        lineHeight: '38px',
        borderRadius: '10px',
        border: 'none',
        background: 'transparent',
        fontSize: '14px',
        fontWeight: 600,
        color: 'var(--color-muted)',
        cursor: 'pointer',
        transition: 'background 0.2s',
    },
    doneBtn: {
        padding: '0 24px',
        height: '38px',
        lineHeight: '38px',
        borderRadius: '10px',
        border: 'none',
        background: 'var(--color-primary)',
        fontSize: '14px',
        fontWeight: 600,
        color: '#fff',
        cursor: 'pointer',
        boxShadow: '0 3px 12px rgba(155, 93, 229, 0.25)',
        transition: 'all 0.2s ease',
    },
};
