import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  contentItem: {
    flexShrink: 0,
    background: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    position: 'relative',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.08)',
    userSelect: 'none',
  },
  contentItemOverlay: {
    content: '""',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '80px',
    background: 'linear-gradient(to top, rgba(0,0,0,0.7), transparent)',
    opacity: 0,
    transition: 'opacity 0.3s ease',
    pointerEvents: 'none',
  },
  contentItemOverlayVisible: {
    opacity: 1,
  },
  contentItemVideo: {
    width: '280px',
    height: '480px',
  },
  contentItemImage: {
    width: '380px',
    height: '220px',
  },
  contentItemHover: {
    transform: 'scale(1.05)',
    boxShadow: '0 8px 28px rgba(0, 0, 0, 0.15)',
    zIndex: 10,
  },
  contentItemDragging: {
    opacity: 0.5,
    cursor: 'grabbing',
  },
  contentThumbnail: {
    width: '100%',
    height: '100%',
    background: 'linear-gradient(135deg, #eef2ff 0%, #faf5ff 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '64px',
    color: theme.colors.primary,
  },
  deleteItemBtn: {
    position: 'absolute',
    top: '10px',
    left: '10px',
    width: '28px',
    height: '28px',
    borderRadius: '8px',
    background: 'rgba(155, 93, 229, 0.1)',
    border: '1px solid',
    borderColor: 'rgba(155, 93, 229, 0.2)',
    color: theme.colors.primary,
    fontSize: '16px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    zIndex: 4,
    padding: 0,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    lineHeight: 1,
  },
  deleteItemBtnVisible: {
    opacity: 1,
  },
  deleteItemBtnHover: {
    background: '#ef4444',
    borderColor: '#dc2626',
    color: 'white',
    transform: 'scale(1.08)',
    boxShadow: '0 2px 8px rgba(239, 68, 68, 0.3)',
  },
  contentActions: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    display: 'flex',
    gap: '8px',
    opacity: 0,
    transition: 'opacity 0.3s ease',
    zIndex: 3,
  },
  contentActionsVisible: {
    opacity: 1,
  },
  actionBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: 'rgba(0, 0, 0, 0.4)',
    backdropFilter: 'blur(10px)',
    border: '1.5px solid',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontSize: '18px',
    color: 'white',
  },
  actionBtnHover: {
    transform: 'scale(1.1)',
    background: 'rgba(0, 0, 0, 0.6)',
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  actionBtnFavoriteActive: {
    background: 'rgba(239, 68, 68, 0.9)',
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  actionBtnFavoriteActiveHover: {
    background: '#ef4444',
    transform: 'scale(1.15)',
  },
  actionBtnWizard: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: theme.gradients.innovator,
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontSize: '18px',
    color: 'white',
    position: 'relative' as const,
  },
  actionBtnWizardHover: {
    transform: 'scale(1.15) rotate(15deg)',
    boxShadow: '0 8px 24px rgba(155, 93, 229, 0.4)',
    filter: 'brightness(1.1)',
  },
  contentTitle: {
    position: 'absolute',
    bottom: '32px',
    left: '20px',
    right: '20px',
    color: 'white',
    fontWeight: 600,
    fontSize: '16px',
    opacity: 0,
    transition: 'opacity 0.3s ease',
    zIndex: 2,
    pointerEvents: 'none',
  },
  contentTitleVisible: {
    opacity: 1,
  },
  contentDate: {
    position: 'absolute',
    bottom: '14px',
    left: '20px',
    right: '20px',
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: '13px',
    fontWeight: 400,
    opacity: 0,
    transition: 'opacity 0.3s ease',
    zIndex: 2,
    pointerEvents: 'none',
  },
  contentDateVisible: {
    opacity: 1,
  },
};