import { CSSProperties } from 'react';
import { theme } from '@theme/theme';

export const styles: Record<string, CSSProperties> = {
  dateNav: {
    background: theme.colors.surface,
    border: '1px solid rgba(251, 191, 36, 0.2)',
    borderRadius: '16px',
    padding: '12px 16px',
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'auto 1fr auto',
    alignItems: 'center',
    marginBottom: '12px',
    boxShadow: '0 2px 12px rgba(251, 191, 36, 0.1)',
  },
  dateLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  dateControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    justifyContent: 'center',
  },
  navArrow: {
    background: 'transparent',
    border: 'none',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '8px 12px',
    borderRadius: '8px',
    transition: 'all 0.2s',
    color: theme.colors.muted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    outline: 'none',
  },
  monthYearDisplay: {
    fontSize: '18px',
    fontWeight: 600,
    color: theme.colors.text,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    borderRadius: '8px',
    transition: 'all 0.2s',
    position: 'relative',
    minWidth: '180px',
    justifyContent: 'center',
  },
  viewToggle: {
    display: 'flex',
    background: 'rgba(155, 93, 229, 0.1)',
    borderRadius: '10px',
    padding: '4px',
  },
  viewBtn: {
    width: '40px',
    height: '36px',
    border: 'none',
    background: 'transparent',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '18px',
    transition: 'all 0.2s',
    color: theme.colors.muted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    outline: 'none',
  },
  viewBtnActive: {
    background: theme.colors.bg,
    color: 'white',
    boxShadow: '0 2px 8px rgba(251, 191, 36, 0.3)',
  },
  tooltip: {
    position: 'absolute',
    bottom: '-32px',
    left: '50%',
    transform: 'translateX(-50%)',
    background: theme.colors.text,
    color: 'white',
    padding: '4px 8px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    pointerEvents: 'none',
    zIndex: 1000,
  },
  createButton: {
    position: 'relative',
    display: 'inline-block',
  },
  createBtn: {
    background: theme.gradients.innovator,
    color: 'white',
    border: `0px solid`,
    padding: '10px 16px',
    borderRadius: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.3s',
    fontSize: '14px',
    outline: 'none',
  },
  createDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: '8px',
    background: theme.colors.surface,
    borderRadius: '12px',
    boxShadow: theme.shadows.lg,
    padding: '8px',
    minWidth: '200px',
    zIndex: 100,
    border: `1px solid ${theme.colors.secondary}`,
  },
  dropdownItem: {
    padding: '12px 16px',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    transition: 'all 0.2s',
  },
  miniCalendar: {
    position: 'absolute',
    top: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    marginTop: '8px',
    background: theme.colors.surface,
    borderRadius: '12px',
    boxShadow: theme.shadows.lg,
    padding: '16px',
    zIndex: 100,
    border: `1px solid ${theme.colors.blue}`,
    minWidth: '280px',
  },
  miniCalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  miniCalNavBtn: {
    background: 'transparent',
    border: 'none',
    fontSize: '20px',
    fontWeight: 'bold',
    cursor: 'pointer',
    padding: '4px 8px',
    color: theme.colors.primary,
    transition: 'all 0.2s',
    borderRadius: '6px',
    outline: 'none',
  },
  miniCalMonthYear: {
    fontSize: '14px',
    fontWeight: 600,
    color: theme.colors.text,
  },
  miniCalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 30px)',
    gap: '4px',
  },
  miniCalDayHeader: {
    fontWeight: 'bold',
    fontSize: '10px',
    textAlign: 'center',
    color: theme.colors.muted,
  },
  miniCalDay: {
    width: '30px',
    height: '30px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '12px',
    transition: 'all 0.2s',
  },
  miniCalDayToday: {
    background: 'rgba(155, 93, 229, 0.15)',
    color: theme.colors.primary,
    fontWeight: 'bold',
    border: `2px solid ${theme.colors.primary}`,
  },
};